<!DOCTYPE html><html>
        <head>
        <title>cmsimde_site</title>
        <meta charset="utf-8">
<meta property="head" content="H2">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link href="https://fonts.googleapis.com/css?family=Quicksand:300,400,500,700,900" rel="stylesheet">
        <link rel="stylesheet" href="./../cmsimde/static/chimper/fonts/icomoon/style.css">
        <link rel="stylesheet" href="./../cmsimde/static/chimper/css/bootstrap.min.css">
        <link rel="stylesheet" href="./../cmsimde/static/chimper/css/magnific-popup.css">
        <link rel="stylesheet" href="./../cmsimde/static/chimper/css/jquery-ui.css">
        <link rel="stylesheet" href="./../cmsimde/static/chimper/css/owl.carousel.min.css">
        <link rel="stylesheet" href="./../cmsimde/static/chimper/css/owl.theme.default.min.css">
        <link rel="stylesheet" href="./../cmsimde/static/chimper/css/bootstrap-datepicker.css">
        <link rel="stylesheet" href="./../cmsimde/static/chimper/fonts/flaticon/font/flaticon.css">
        <link rel="stylesheet" href="./../cmsimde/static/chimper/css/aos.css">
        <link rel="stylesheet" href="./../cmsimde/static/chimper/css/style.css">
        <link rel="shortcut icon" href="./../cmsimde/static/favicons.png">

        <style type='text/css'>
            .site-section {
            background-color: #FFFF;
            padding: 40px 40px;
            }
            body > div > div.dropdown.open {
                display: block;
            }
        </style>
    
        <!-- <script src="./../cmsimde/static/jquery.js"></script> -->
        <!-- <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script> -->
        <script src="../cmsimde/static/chimper/js/jquery-3.3.1.min.js"></script>
        <link rel="stylesheet" href="./../cmsimde/static/tipuesearch/css/normalize.min.css">
        <script src="./../cmsimde/static/tipuesearch/tipuesearch_set.js"></script>
        <script src="tipuesearch_content.js"></script>
        <link rel="stylesheet" href="./../cmsimde/static/tipuesearch/css/tipuesearch.css">
        <script src="./../cmsimde/static/tipuesearch/tipuesearch.js"></script>
        <!-- for Wink3 客製化關閉 -->
        <!--
        <link rel="stylesheet" type="text/css" href="./../cmsimde/static/winkPlayer.css" />
        <script type="text/javascript" src="./../cmsimde/static/winkPlayer.js"></script>
        -->
        <script>
            /* original tipuesearch
            $(document).ready(function() {
                 $('#tipue_search_input').tipuesearch();
            });
            */
            // customed doSearch
            function doSearch() {
                $('#tipue_search_input').tipuesearch({
                    newWindow: true, 
                    minimumLength: 2,
                    wholeWords: false, // for search 中文
                });
            }
            $(document).ready(doSearch);
        </script>
        
<script type="text/javascript" src="./../cmsimde/static/syntaxhighlighter/shCore.js"></script>
<script type="text/javascript" src="./../cmsimde/static/syntaxhighlighter/shBrushBash.js"></script>
<script type="text/javascript" src="./../cmsimde/static/syntaxhighlighter/shBrushDiff.js"></script>
<script type="text/javascript" src="./../cmsimde/static/syntaxhighlighter/shBrushJScript.js"></script>
<script type="text/javascript" src="./../cmsimde/static/syntaxhighlighter/shBrushJava.js"></script>
<script type="text/javascript" src="./../cmsimde/static/syntaxhighlighter/shBrushPython.js"></script>
<script type="text/javascript" src="./../cmsimde/static/syntaxhighlighter/shBrushSql.js"></script>
<script type="text/javascript" src="./../cmsimde/static/syntaxhighlighter/shBrushHaxe.js"></script>
<script type="text/javascript" src="./../cmsimde/static/syntaxhighlighter/shBrushXml.js"></script>
<script type="text/javascript" src="./../cmsimde/static/syntaxhighlighter/shBrushPhp.js"></script>
<script type="text/javascript" src="./../cmsimde/static/syntaxhighlighter/shBrushPowerShell.js"></script>
<script type="text/javascript" src="./../cmsimde/static/syntaxhighlighter/shBrushLua.js"></script>
<script type="text/javascript" src="./../cmsimde/static/syntaxhighlighter/shBrushMojo.js"></script>
<script type="text/javascript" src="./../cmsimde/static/syntaxhighlighter/shBrushCpp.js"></script>
<script type="text/javascript" src="./../cmsimde/static/syntaxhighlighter/shBrushCss.js"></script>
<script type="text/javascript" src="./../cmsimde/static/syntaxhighlighter/shBrushCSharp.js"></script>
<script type="text/javascript" src="./../cmsimde/static/syntaxhighlighter/shBrushDart.js"></script>
<script type="text/javascript" src="./../cmsimde/static/syntaxhighlighter/shBrushRust.js"></script>
<link type="text/css" rel="stylesheet" href="./../cmsimde/static/syntaxhighlighter/css/shCoreDefault.css"/>
<script type="text/javascript">SyntaxHighlighter.all();</script>
<!-- 暫時不用
<script src="./../cmsimde/static/fengari-web.js"></script>
<script type="text/javascript" src="./../cmsimde/static/Cango-13v08-min.js"></script>
<script type="text/javascript" src="./../cmsimde/static/CangoAxes-4v01-min.js"></script>
<script type="text/javascript" src="./../cmsimde/static/gearUtils-05.js"></script>
-->
<!-- for Brython 暫時不用
<script src="https://scrum-3.github.io/web/brython/brython.js"></script>
<script src="https://scrum-3.github.io/web/brython/brython_stdlib.js"></script>
-->
<style>
img.add_border {
    border: 3px solid blue;
}
</style>

</head>
<body>
<div class='container'><nav>
        
    <div class="site-wrap">

    <div class="site-mobile-menu">
      <div class="site-mobile-menu-header">
        <div class="site-mobile-menu-close mt-3">
          <span class="icon-close2 js-menu-toggle"></span>
        </div>
      </div>
      <div class="site-mobile-menu-body"></div>
    </div>

            <header class="site-navbar py-4 bg-white" role="banner">
              <div class="container">
                <div class="row align-items-center">
                <h1>41123207 cd2024</h1>
                <div class="pl-4">
                    <form>
                    <input type="text" placeholder="Search" name="q" id="tipue_search_input" pattern=".{2,}" title="At least 2 characters" required>
                    </form>
                </div>
                  <!-- <div class="col-11 col-xl-2">
                    <h1 class="mb-0 site-logo"><a href="index.html" class="text-black h2 mb-0">41123207 cd2024</a></h1> 
                  </div>
                  -->
                  <div class="col-12 col-md-10 d-none d-xl-block">
                    <nav class="site-navigation position-relative text-right" role="navigation">
    <ul class='site-menu js-clone-nav mr-auto d-none d-lg-block'>
                        <li class="active has-children"><a href="index.html">Home</a>
                        <ul class="dropdown">
                            <li><a href="sitemap.html">SMap</a></li>
                            <li><a href="./../reveal/index.html">reveal</a></li>
                            <li><a href="./../blog/index.html">blog</a></li>
                        </ul>
                      </li>
                     <li><a href='About.html'>About</a><li><a href='cmsimde.html'>cmsimde</a><li><a href='Replit.html'>Replit</a><li><a href='Brython.html'>Brython</a><li class='has-children'><a href='w17.html'>w17</a><ul class='dropdown'><li><a href='H1.html'>H1</a><li><a href='H2.html'>H2</a><li><a href='H3.html'>H3</a></li></ul><li class='has-children'><a href='NX.html'>NX</a><ul class='dropdown'><li><a href='nxopen w12 實習任務一.html'>nxopen w12 實習任務一</a><li><a href='nxopen 組合零件.html'>nxopen 組合零件</a></li></ul><li class='has-children'><a href='PID 控制文獻整理.html'>PID 控制文獻整理</a><ul class='dropdown'><li><a href='與詳細重點摘要.html'>與詳細重點摘要</a></li></ul><li><a href='都靈理工大學.html'>都靈理工大學</a><li><a href='鋼球平衡台控制模擬.html'>鋼球平衡台控制模擬</a><li><a href='教學影片分組整理.html'>教學影片分組整理</a><li><a href='教學影片分組整理逐字稿.html'>教學影片分組整理逐字稿</a></li>
                      </ul>
                </nav>
              </div>
              <div class="d-inline-block d-xl-none ml-md-0 mr-auto py-3" style="position: relative; top: 3px;"><a href="#" class="site-menu-toggle js-menu-toggle text-black"><span class="icon-menu h3"></span></a></div>
              </div>

            </div>
          </div>

        </header>
    <div id="tipue_search_content">NX << <a href='NX.html'>Previous</a> <a href='nxopen 組合零件.html'>Next</a> >> nxopen 組合零件<br /><h1>nxopen w12 實習任務一</h1>
<p><a href="https://nfuedu-my.sharepoint.com/:u:/g/personal/41123207_nfu_edu_tw/EQJdS7P7A69MsJtAr_IrJI4BvqLRPWEuodDvoKcwlhLlRQ?e=Zzl0PO"><span mce-data-marked="1">NO.4 RECORD.vb</span></a></p>
<div>
<div><span mce-data-marked="1">' NX 1872</span></div>
<div><span mce-data-marked="1">' Journal created by Admin on Thu May 9 15:20:28 2024 台北標準時間</span></div>
<br/>
<div><span mce-data-marked="1">'</span></div>
<div><span mce-data-marked="1">Imports</span><span mce-data-marked="1"> System</span></div>
<div><span mce-data-marked="1">Imports</span><span mce-data-marked="1"> NXOpen</span></div>
<br/>
<div><span mce-data-marked="1">Module</span><span mce-data-marked="1"> NXJournal</span></div>
<div><span mce-data-marked="1">Sub</span><span mce-data-marked="1"> Main (</span><span mce-data-marked="1">ByVal</span><span mce-data-marked="1"> args() </span><span mce-data-marked="1">As</span><span mce-data-marked="1"> </span><span mce-data-marked="1">String</span><span mce-data-marked="1">) </span></div>
<br/>
<div><span mce-data-marked="1">Dim</span><span mce-data-marked="1"> theSession </span><span mce-data-marked="1">As</span><span mce-data-marked="1"> NXOpen.Session = NXOpen.Session.GetSession()</span></div>
<div><span mce-data-marked="1">Dim</span><span mce-data-marked="1"> workPart </span><span mce-data-marked="1">As</span><span mce-data-marked="1"> NXOpen.Part = theSession.Parts.Work</span></div>
<br/>
<div><span mce-data-marked="1">Dim</span><span mce-data-marked="1"> displayPart </span><span mce-data-marked="1">As</span><span mce-data-marked="1"> NXOpen.Part = theSession.Parts.Display</span></div>
<br/>
<div><span mce-data-marked="1">' ----------------------------------------------</span></div>
<div><span mce-data-marked="1">' 功能表：插入(S)-&gt;基準/點(D)-&gt;基準平面(D)...</span></div>
<div><span mce-data-marked="1">' ----------------------------------------------</span></div>
<div><span mce-data-marked="1">Dim</span><span mce-data-marked="1"> markId1 </span><span mce-data-marked="1">As</span><span mce-data-marked="1"> NXOpen.Session.UndoMarkId = </span><span mce-data-marked="1">Nothing</span></div>
<div><span mce-data-marked="1">markId1 = theSession.SetUndoMark(NXOpen.Session.MarkVisibility.Visible, </span><span mce-data-marked="1">"起點"</span><span mce-data-marked="1">)</span></div>
<br/>
<div><span mce-data-marked="1">Dim</span><span mce-data-marked="1"> nullNXOpen_Features_Feature </span><span mce-data-marked="1">As</span><span mce-data-marked="1"> NXOpen.Features.Feature = </span><span mce-data-marked="1">Nothing</span></div>
<br/>
<div><span mce-data-marked="1">Dim</span><span mce-data-marked="1"> datumPlaneBuilder1 </span><span mce-data-marked="1">As</span><span mce-data-marked="1"> NXOpen.Features.DatumPlaneBuilder = </span><span mce-data-marked="1">Nothing</span></div>
<div><span mce-data-marked="1">datumPlaneBuilder1 = workPart.Features.CreateDatumPlaneBuilder(nullNXOpen_Features_Feature)</span></div>
<br/>
<div><span mce-data-marked="1">Dim</span><span mce-data-marked="1"> plane1 </span><span mce-data-marked="1">As</span><span mce-data-marked="1"> NXOpen.Plane = </span><span mce-data-marked="1">Nothing</span></div>
<div><span mce-data-marked="1">plane1 = datumPlaneBuilder1.GetPlane()</span></div>
<br/>
<div><span mce-data-marked="1">Dim</span><span mce-data-marked="1"> unit1 </span><span mce-data-marked="1">As</span><span mce-data-marked="1"> NXOpen.Unit = </span><span mce-data-marked="1">CType</span><span mce-data-marked="1">(workPart.UnitCollection.FindObject(</span><span mce-data-marked="1">"MilliMeter"</span><span mce-data-marked="1">), NXOpen.Unit)</span></div>
<br/>
<div><span mce-data-marked="1">Dim</span><span mce-data-marked="1"> expression1 </span><span mce-data-marked="1">As</span><span mce-data-marked="1"> NXOpen.Expression = </span><span mce-data-marked="1">Nothing</span></div>
<div><span mce-data-marked="1">expression1 = workPart.Expressions.CreateSystemExpressionWithUnits(</span><span mce-data-marked="1">"0"</span><span mce-data-marked="1">, unit1)</span></div>
<br/>
<div><span mce-data-marked="1">Dim</span><span mce-data-marked="1"> expression2 </span><span mce-data-marked="1">As</span><span mce-data-marked="1"> NXOpen.Expression = </span><span mce-data-marked="1">Nothing</span></div>
<div><span mce-data-marked="1">expression2 = workPart.Expressions.CreateSystemExpressionWithUnits(</span><span mce-data-marked="1">"0"</span><span mce-data-marked="1">, unit1)</span></div>
<br/>
<div><span mce-data-marked="1">Dim</span><span mce-data-marked="1"> coordinates1 </span><span mce-data-marked="1">As</span><span mce-data-marked="1"> NXOpen.Point3d = </span><span mce-data-marked="1">New</span><span mce-data-marked="1"> NXOpen.Point3d(</span><span mce-data-marked="1">0.0</span><span mce-data-marked="1">, </span><span mce-data-marked="1">0.0</span><span mce-data-marked="1">, </span><span mce-data-marked="1">0.0</span><span mce-data-marked="1">)</span></div>
<div><span mce-data-marked="1">Dim</span><span mce-data-marked="1"> point1 </span><span mce-data-marked="1">As</span><span mce-data-marked="1"> NXOpen.Point = </span><span mce-data-marked="1">Nothing</span></div>
<div><span mce-data-marked="1">point1 = workPart.Points.CreatePoint(coordinates1)</span></div>
<br/>
<div><span mce-data-marked="1">theSession.SetUndoMarkName(markId1, </span><span mce-data-marked="1">"基準平面 對話方塊"</span><span mce-data-marked="1">)</span></div>
<br/>
<div><span mce-data-marked="1">plane1.SetUpdateOption(NXOpen.SmartObject.UpdateOption.WithinModeling)</span></div>
<br/>
<div><span mce-data-marked="1">' ----------------------------------------------</span></div>
<div><span mce-data-marked="1">' 功能表：插入(S)-&gt;基準/點(D)-&gt;基準座標系(C)...</span></div>
<div><span mce-data-marked="1">' ----------------------------------------------</span></div>
<div><span mce-data-marked="1">datumPlaneBuilder1.Destroy()</span></div>
<br/>
<div><span mce-data-marked="1">Try</span></div>
<div><span mce-data-marked="1"> </span><span mce-data-marked="1">' 運算式仍然在使用中。</span></div>
<div><span mce-data-marked="1"> workPart.Expressions.Delete(expression2)</span></div>
<div><span mce-data-marked="1">Catch</span><span mce-data-marked="1"> ex </span><span mce-data-marked="1">As</span><span mce-data-marked="1"> NXException</span></div>
<div><span mce-data-marked="1"> ex.AssertErrorCode(</span><span mce-data-marked="1">1050029</span><span mce-data-marked="1">)</span></div>
<div><span mce-data-marked="1">End Try</span></div>
<br/>
<div><span mce-data-marked="1">Try</span></div>
<div><span mce-data-marked="1"> </span><span mce-data-marked="1">' 運算式仍然在使用中。</span></div>
<div><span mce-data-marked="1"> workPart.Expressions.Delete(expression1)</span></div>
<div><span mce-data-marked="1">Catch</span><span mce-data-marked="1"> ex </span><span mce-data-marked="1">As</span><span mce-data-marked="1"> NXException</span></div>
<div><span mce-data-marked="1"> ex.AssertErrorCode(</span><span mce-data-marked="1">1050029</span><span mce-data-marked="1">)</span></div>
<div><span mce-data-marked="1">End Try</span></div>
<br/>
<div><span mce-data-marked="1">theSession.UndoToMark(markId1, </span><span mce-data-marked="1">Nothing</span><span mce-data-marked="1">)</span></div>
<br/>
<div><span mce-data-marked="1">theSession.DeleteUndoMark(markId1, </span><span mce-data-marked="1">Nothing</span><span mce-data-marked="1">)</span></div>
<br/>
<div><span mce-data-marked="1">Dim</span><span mce-data-marked="1"> markId2 </span><span mce-data-marked="1">As</span><span mce-data-marked="1"> NXOpen.Session.UndoMarkId = </span><span mce-data-marked="1">Nothing</span></div>
<div><span mce-data-marked="1">markId2 = theSession.SetUndoMark(NXOpen.Session.MarkVisibility.Visible, </span><span mce-data-marked="1">"起點"</span><span mce-data-marked="1">)</span></div>
<br/>
<div><span mce-data-marked="1">Dim</span><span mce-data-marked="1"> datumCsysBuilder1 </span><span mce-data-marked="1">As</span><span mce-data-marked="1"> NXOpen.Features.DatumCsysBuilder = </span><span mce-data-marked="1">Nothing</span></div>
<div><span mce-data-marked="1">datumCsysBuilder1 = workPart.Features.CreateDatumCsysBuilder(nullNXOpen_Features_Feature)</span></div>
<br/>
<div><span mce-data-marked="1">Dim</span><span mce-data-marked="1"> origin1 </span><span mce-data-marked="1">As</span><span mce-data-marked="1"> NXOpen.Point3d = </span><span mce-data-marked="1">New</span><span mce-data-marked="1"> NXOpen.Point3d(</span><span mce-data-marked="1">0.0</span><span mce-data-marked="1">, </span><span mce-data-marked="1">0.0</span><span mce-data-marked="1">, </span><span mce-data-marked="1">0.0</span><span mce-data-marked="1">)</span></div>
<div><span mce-data-marked="1">Dim</span><span mce-data-marked="1"> normal1 </span><span mce-data-marked="1">As</span><span mce-data-marked="1"> NXOpen.Vector3d = </span><span mce-data-marked="1">New</span><span mce-data-marked="1"> NXOpen.Vector3d(</span><span mce-data-marked="1">0.0</span><span mce-data-marked="1">, </span><span mce-data-marked="1">0.0</span><span mce-data-marked="1">, </span><span mce-data-marked="1">1.0</span><span mce-data-marked="1">)</span></div>
<div><span mce-data-marked="1">Dim</span><span mce-data-marked="1"> plane2 </span><span mce-data-marked="1">As</span><span mce-data-marked="1"> NXOpen.Plane = </span><span mce-data-marked="1">Nothing</span></div>
<div><span mce-data-marked="1">plane2 = workPart.Planes.CreatePlane(origin1, normal1, NXOpen.SmartObject.UpdateOption.WithinModeling)</span></div>
<br/>
<div><span mce-data-marked="1">Dim</span><span mce-data-marked="1"> expression3 </span><span mce-data-marked="1">As</span><span mce-data-marked="1"> NXOpen.Expression = </span><span mce-data-marked="1">Nothing</span></div>
<div><span mce-data-marked="1">expression3 = workPart.Expressions.CreateSystemExpressionWithUnits(</span><span mce-data-marked="1">"0"</span><span mce-data-marked="1">, unit1)</span></div>
<br/>
<div><span mce-data-marked="1">Dim</span><span mce-data-marked="1"> expression4 </span><span mce-data-marked="1">As</span><span mce-data-marked="1"> NXOpen.Expression = </span><span mce-data-marked="1">Nothing</span></div>
<div><span mce-data-marked="1">expression4 = workPart.Expressions.CreateSystemExpressionWithUnits(</span><span mce-data-marked="1">"0"</span><span mce-data-marked="1">, unit1)</span></div>
<br/>
<div><span mce-data-marked="1">Dim</span><span mce-data-marked="1"> origin2 </span><span mce-data-marked="1">As</span><span mce-data-marked="1"> NXOpen.Point3d = </span><span mce-data-marked="1">New</span><span mce-data-marked="1"> NXOpen.Point3d(</span><span mce-data-marked="1">0.0</span><span mce-data-marked="1">, </span><span mce-data-marked="1">0.0</span><span mce-data-marked="1">, </span><span mce-data-marked="1">0.0</span><span mce-data-marked="1">)</span></div>
<div><span mce-data-marked="1">Dim</span><span mce-data-marked="1"> normal2 </span><span mce-data-marked="1">As</span><span mce-data-marked="1"> NXOpen.Vector3d = </span><span mce-data-marked="1">New</span><span mce-data-marked="1"> NXOpen.Vector3d(</span><span mce-data-marked="1">0.0</span><span mce-data-marked="1">, </span><span mce-data-marked="1">0.0</span><span mce-data-marked="1">, </span><span mce-data-marked="1">1.0</span><span mce-data-marked="1">)</span></div>
<div><span mce-data-marked="1">Dim</span><span mce-data-marked="1"> plane3 </span><span mce-data-marked="1">As</span><span mce-data-marked="1"> NXOpen.Plane = </span><span mce-data-marked="1">Nothing</span></div>
<div><span mce-data-marked="1">plane3 = workPart.Planes.CreatePlane(origin2, normal2, NXOpen.SmartObject.UpdateOption.WithinModeling)</span></div>
<br/>
<div><span mce-data-marked="1">Dim</span><span mce-data-marked="1"> expression5 </span><span mce-data-marked="1">As</span><span mce-data-marked="1"> NXOpen.Expression = </span><span mce-data-marked="1">Nothing</span></div>
<div><span mce-data-marked="1">expression5 = workPart.Expressions.CreateSystemExpressionWithUnits(</span><span mce-data-marked="1">"0"</span><span mce-data-marked="1">, unit1)</span></div>
<br/>
<div><span mce-data-marked="1">Dim</span><span mce-data-marked="1"> expression6 </span><span mce-data-marked="1">As</span><span mce-data-marked="1"> NXOpen.Expression = </span><span mce-data-marked="1">Nothing</span></div>
<div><span mce-data-marked="1">expression6 = workPart.Expressions.CreateSystemExpressionWithUnits(</span><span mce-data-marked="1">"0"</span><span mce-data-marked="1">, unit1)</span></div>
<br/>
<div><span mce-data-marked="1">Dim</span><span mce-data-marked="1"> origin3 </span><span mce-data-marked="1">As</span><span mce-data-marked="1"> NXOpen.Point3d = </span><span mce-data-marked="1">New</span><span mce-data-marked="1"> NXOpen.Point3d(</span><span mce-data-marked="1">0.0</span><span mce-data-marked="1">, </span><span mce-data-marked="1">0.0</span><span mce-data-marked="1">, </span><span mce-data-marked="1">0.0</span><span mce-data-marked="1">)</span></div>
<div><span mce-data-marked="1">Dim</span><span mce-data-marked="1"> normal3 </span><span mce-data-marked="1">As</span><span mce-data-marked="1"> NXOpen.Vector3d = </span><span mce-data-marked="1">New</span><span mce-data-marked="1"> NXOpen.Vector3d(</span><span mce-data-marked="1">0.0</span><span mce-data-marked="1">, </span><span mce-data-marked="1">0.0</span><span mce-data-marked="1">, </span><span mce-data-marked="1">1.0</span><span mce-data-marked="1">)</span></div>
<div><span mce-data-marked="1">Dim</span><span mce-data-marked="1"> plane4 </span><span mce-data-marked="1">As</span><span mce-data-marked="1"> NXOpen.Plane = </span><span mce-data-marked="1">Nothing</span></div>
<div><span mce-data-marked="1">plane4 = workPart.Planes.CreatePlane(origin3, normal3, NXOpen.SmartObject.UpdateOption.WithinModeling)</span></div>
<br/>
<div><span mce-data-marked="1">Dim</span><span mce-data-marked="1"> expression7 </span><span mce-data-marked="1">As</span><span mce-data-marked="1"> NXOpen.Expression = </span><span mce-data-marked="1">Nothing</span></div>
<div><span mce-data-marked="1">expression7 = workPart.Expressions.CreateSystemExpressionWithUnits(</span><span mce-data-marked="1">"0"</span><span mce-data-marked="1">, unit1)</span></div>
<br/>
<div><span mce-data-marked="1">Dim</span><span mce-data-marked="1"> expression8 </span><span mce-data-marked="1">As</span><span mce-data-marked="1"> NXOpen.Expression = </span><span mce-data-marked="1">Nothing</span></div>
<div><span mce-data-marked="1">expression8 = workPart.Expressions.CreateSystemExpressionWithUnits(</span><span mce-data-marked="1">"0"</span><span mce-data-marked="1">, unit1)</span></div>
<br/>
<div><span mce-data-marked="1">Dim</span><span mce-data-marked="1"> origin4 </span><span mce-data-marked="1">As</span><span mce-data-marked="1"> NXOpen.Point3d = </span><span mce-data-marked="1">New</span><span mce-data-marked="1"> NXOpen.Point3d(</span><span mce-data-marked="1">0.0</span><span mce-data-marked="1">, </span><span mce-data-marked="1">0.0</span><span mce-data-marked="1">, </span><span mce-data-marked="1">0.0</span><span mce-data-marked="1">)</span></div>
<div><span mce-data-marked="1">Dim</span><span mce-data-marked="1"> normal4 </span><span mce-data-marked="1">As</span><span mce-data-marked="1"> NXOpen.Vector3d = </span><span mce-data-marked="1">New</span><span mce-data-marked="1"> NXOpen.Vector3d(</span><span mce-data-marked="1">0.0</span><span mce-data-marked="1">, </span><span mce-data-marked="1">0.0</span><span mce-data-marked="1">, </span><span mce-data-marked="1">1.0</span><span mce-data-marked="1">)</span></div>
<div><span mce-data-marked="1">Dim</span><span mce-data-marked="1"> plane5 </span><span mce-data-marked="1">As</span><span mce-data-marked="1"> NXOpen.Plane = </span><span mce-data-marked="1">Nothing</span></div>
<div><span mce-data-marked="1">plane5 = workPart.Planes.CreatePlane(origin4, normal4, NXOpen.SmartObject.UpdateOption.WithinModeling)</span></div>
<br/>
<div><span mce-data-marked="1">Dim</span><span mce-data-marked="1"> expression9 </span><span mce-data-marked="1">As</span><span mce-data-marked="1"> NXOpen.Expression = </span><span mce-data-marked="1">Nothing</span></div>
<div><span mce-data-marked="1">expression9 = workPart.Expressions.CreateSystemExpressionWithUnits(</span><span mce-data-marked="1">"0"</span><span mce-data-marked="1">, unit1)</span></div>
<br/>
<div><span mce-data-marked="1">Dim</span><span mce-data-marked="1"> expression10 </span><span mce-data-marked="1">As</span><span mce-data-marked="1"> NXOpen.Expression = </span><span mce-data-marked="1">Nothing</span></div>
<div><span mce-data-marked="1">expression10 = workPart.Expressions.CreateSystemExpressionWithUnits(</span><span mce-data-marked="1">"0"</span><span mce-data-marked="1">, unit1)</span></div>
<br/>
<div><span mce-data-marked="1">Dim</span><span mce-data-marked="1"> unit2 </span><span mce-data-marked="1">As</span><span mce-data-marked="1"> NXOpen.Unit = </span><span mce-data-marked="1">CType</span><span mce-data-marked="1">(workPart.UnitCollection.FindObject(</span><span mce-data-marked="1">"Degrees"</span><span mce-data-marked="1">), NXOpen.Unit)</span></div>
<br/>
<div><span mce-data-marked="1">Dim</span><span mce-data-marked="1"> expression11 </span><span mce-data-marked="1">As</span><span mce-data-marked="1"> NXOpen.Expression = </span><span mce-data-marked="1">Nothing</span></div>
<div><span mce-data-marked="1">expression11 = workPart.Expressions.CreateSystemExpressionWithUnits(</span><span mce-data-marked="1">"0"</span><span mce-data-marked="1">, unit2)</span></div>
<br/>
<div><span mce-data-marked="1">Dim</span><span mce-data-marked="1"> expression12 </span><span mce-data-marked="1">As</span><span mce-data-marked="1"> NXOpen.Expression = </span><span mce-data-marked="1">Nothing</span></div>
<div><span mce-data-marked="1">expression12 = workPart.Expressions.CreateSystemExpressionWithUnits(</span><span mce-data-marked="1">"0"</span><span mce-data-marked="1">, unit2)</span></div>
<br/>
<div><span mce-data-marked="1">Dim</span><span mce-data-marked="1"> expression13 </span><span mce-data-marked="1">As</span><span mce-data-marked="1"> NXOpen.Expression = </span><span mce-data-marked="1">Nothing</span></div>
<div><span mce-data-marked="1">expression13 = workPart.Expressions.CreateSystemExpressionWithUnits(</span><span mce-data-marked="1">"0"</span><span mce-data-marked="1">, unit2)</span></div>
<br/>
<div><span mce-data-marked="1">Dim</span><span mce-data-marked="1"> expression14 </span><span mce-data-marked="1">As</span><span mce-data-marked="1"> NXOpen.Expression = </span><span mce-data-marked="1">Nothing</span></div>
<div><span mce-data-marked="1">expression14 = workPart.Expressions.CreateSystemExpressionWithUnits(</span><span mce-data-marked="1">"0"</span><span mce-data-marked="1">, unit1)</span></div>
<br/>
<div><span mce-data-marked="1">Dim</span><span mce-data-marked="1"> expression15 </span><span mce-data-marked="1">As</span><span mce-data-marked="1"> NXOpen.Expression = </span><span mce-data-marked="1">Nothing</span></div>
<div><span mce-data-marked="1">expression15 = workPart.Expressions.CreateSystemExpressionWithUnits(</span><span mce-data-marked="1">"0"</span><span mce-data-marked="1">, unit2)</span></div>
<br/>
<div><span mce-data-marked="1">Dim</span><span mce-data-marked="1"> expression16 </span><span mce-data-marked="1">As</span><span mce-data-marked="1"> NXOpen.Expression = </span><span mce-data-marked="1">Nothing</span></div>
<div><span mce-data-marked="1">expression16 = workPart.Expressions.CreateSystemExpressionWithUnits(</span><span mce-data-marked="1">"0"</span><span mce-data-marked="1">, unit1)</span></div>
<br/>
<div><span mce-data-marked="1">Dim</span><span mce-data-marked="1"> expression17 </span><span mce-data-marked="1">As</span><span mce-data-marked="1"> NXOpen.Expression = </span><span mce-data-marked="1">Nothing</span></div>
<div><span mce-data-marked="1">expression17 = workPart.Expressions.CreateSystemExpressionWithUnits(</span><span mce-data-marked="1">"0"</span><span mce-data-marked="1">, unit2)</span></div>
<br/>
<div><span mce-data-marked="1">Dim</span><span mce-data-marked="1"> expression18 </span><span mce-data-marked="1">As</span><span mce-data-marked="1"> NXOpen.Expression = </span><span mce-data-marked="1">Nothing</span></div>
<div><span mce-data-marked="1">expression18 = workPart.Expressions.CreateSystemExpressionWithUnits(</span><span mce-data-marked="1">"0"</span><span mce-data-marked="1">, unit1)</span></div>
<br/>
<div><span mce-data-marked="1">Dim</span><span mce-data-marked="1"> expression19 </span><span mce-data-marked="1">As</span><span mce-data-marked="1"> NXOpen.Expression = </span><span mce-data-marked="1">Nothing</span></div>
<div><span mce-data-marked="1">expression19 = workPart.Expressions.CreateSystemExpressionWithUnits(</span><span mce-data-marked="1">"0"</span><span mce-data-marked="1">, unit2)</span></div>
<br/>
<div><span mce-data-marked="1">expression14.RightHandSide = </span><span mce-data-marked="1">"0"</span></div>
<br/>
<div><span mce-data-marked="1">expression16.RightHandSide = </span><span mce-data-marked="1">"0"</span></div>
<br/>
<div><span mce-data-marked="1">expression18.RightHandSide = </span><span mce-data-marked="1">"0"</span></div>
<br/>
<div><span mce-data-marked="1">expression15.RightHandSide = </span><span mce-data-marked="1">"0"</span></div>
<br/>
<div><span mce-data-marked="1">expression17.RightHandSide = </span><span mce-data-marked="1">"0"</span></div>
<br/>
<div><span mce-data-marked="1">expression19.RightHandSide = </span><span mce-data-marked="1">"0"</span></div>
<br/>
<div><span mce-data-marked="1">theSession.SetUndoMarkName(markId2, </span><span mce-data-marked="1">"基準座標系 對話方塊"</span><span mce-data-marked="1">)</span></div>
<br/>
<div><span mce-data-marked="1">' ----------------------------------------------</span></div>
<div><span mce-data-marked="1">' 功能表：插入(S)-&gt;草圖(H)...</span></div>
<div><span mce-data-marked="1">' ----------------------------------------------</span></div>
<div><span mce-data-marked="1">Dim</span><span mce-data-marked="1"> markId3 </span><span mce-data-marked="1">As</span><span mce-data-marked="1"> NXOpen.Session.UndoMarkId = </span><span mce-data-marked="1">Nothing</span></div>
<div><span mce-data-marked="1">markId3 = theSession.SetUndoMark(NXOpen.Session.MarkVisibility.Invisible, </span><span mce-data-marked="1">"基準座標系"</span><span mce-data-marked="1">)</span></div>
<br/>
<div><span mce-data-marked="1">theSession.DeleteUndoMark(markId3, </span><span mce-data-marked="1">Nothing</span><span mce-data-marked="1">)</span></div>
<br/>
<div><span mce-data-marked="1">Dim</span><span mce-data-marked="1"> markId4 </span><span mce-data-marked="1">As</span><span mce-data-marked="1"> NXOpen.Session.UndoMarkId = </span><span mce-data-marked="1">Nothing</span></div>
<div><span mce-data-marked="1">markId4 = theSession.SetUndoMark(NXOpen.Session.MarkVisibility.Invisible, </span><span mce-data-marked="1">"基準座標系"</span><span mce-data-marked="1">)</span></div>
<br/>
<div><span mce-data-marked="1">Dim</span><span mce-data-marked="1"> origin5 </span><span mce-data-marked="1">As</span><span mce-data-marked="1"> NXOpen.Point3d = </span><span mce-data-marked="1">New</span><span mce-data-marked="1"> NXOpen.Point3d(</span><span mce-data-marked="1">0.0</span><span mce-data-marked="1">, </span><span mce-data-marked="1">0.0</span><span mce-data-marked="1">, </span><span mce-data-marked="1">0.0</span><span mce-data-marked="1">)</span></div>
<div><span mce-data-marked="1">Dim</span><span mce-data-marked="1"> xDirection1 </span><span mce-data-marked="1">As</span><span mce-data-marked="1"> NXOpen.Vector3d = </span><span mce-data-marked="1">New</span><span mce-data-marked="1"> NXOpen.Vector3d(</span><span mce-data-marked="1">1.0</span><span mce-data-marked="1">, </span><span mce-data-marked="1">0.0</span><span mce-data-marked="1">, </span><span mce-data-marked="1">0.0</span><span mce-data-marked="1">)</span></div>
<div><span mce-data-marked="1">Dim</span><span mce-data-marked="1"> yDirection1 </span><span mce-data-marked="1">As</span><span mce-data-marked="1"> NXOpen.Vector3d = </span><span mce-data-marked="1">New</span><span mce-data-marked="1"> NXOpen.Vector3d(</span><span mce-data-marked="1">0.0</span><span mce-data-marked="1">, </span><span mce-data-marked="1">1.0</span><span mce-data-marked="1">, </span><span mce-data-marked="1">0.0</span><span mce-data-marked="1">)</span></div>
<div><span mce-data-marked="1">Dim</span><span mce-data-marked="1"> xform1 </span><span mce-data-marked="1">As</span><span mce-data-marked="1"> NXOpen.Xform = </span><span mce-data-marked="1">Nothing</span></div>
<div><span mce-data-marked="1">xform1 = workPart.Xforms.CreateXform(origin5, xDirection1, yDirection1, NXOpen.SmartObject.UpdateOption.WithinModeling, </span><span mce-data-marked="1">1.0</span><span mce-data-marked="1">)</span></div>
<br/>
<div><span mce-data-marked="1">Dim</span><span mce-data-marked="1"> cartesianCoordinateSystem1 </span><span mce-data-marked="1">As</span><span mce-data-marked="1"> NXOpen.CartesianCoordinateSystem = </span><span mce-data-marked="1">Nothing</span></div>
<div><span mce-data-marked="1">cartesianCoordinateSystem1 = workPart.CoordinateSystems.CreateCoordinateSystem(xform1, NXOpen.SmartObject.UpdateOption.WithinModeling)</span></div>
<br/>
<div><span mce-data-marked="1">theSession.DeleteUndoMark(markId4, </span><span mce-data-marked="1">Nothing</span><span mce-data-marked="1">)</span></div>
<br/>
<div><span mce-data-marked="1">theSession.SetUndoMarkName(markId2, </span><span mce-data-marked="1">"基準座標系"</span><span mce-data-marked="1">)</span></div>
<br/>
<div><span mce-data-marked="1">workPart.Expressions.Delete(expression14)</span></div>
<br/>
<div><span mce-data-marked="1">workPart.Expressions.Delete(expression16)</span></div>
<br/>
<div><span mce-data-marked="1">workPart.Expressions.Delete(expression18)</span></div>
<br/>
<div><span mce-data-marked="1">workPart.Expressions.Delete(expression15)</span></div>
<br/>
<div><span mce-data-marked="1">workPart.Expressions.Delete(expression17)</span></div>
<br/>
<div><span mce-data-marked="1">workPart.Expressions.Delete(expression19)</span></div>
<br/>
<div><span mce-data-marked="1">workPart.Expressions.Delete(expression11)</span></div>
<br/>
<div><span mce-data-marked="1">workPart.Expressions.Delete(expression12)</span></div>
<br/>
<div><span mce-data-marked="1">workPart.Expressions.Delete(expression13)</span></div>
<br/>
<div><span mce-data-marked="1">Try</span></div>
<div><span mce-data-marked="1"> </span><span mce-data-marked="1">' 運算式仍然在使用中。</span></div>
<div><span mce-data-marked="1"> workPart.Expressions.Delete(expression4)</span></div>
<div><span mce-data-marked="1">Catch</span><span mce-data-marked="1"> ex </span><span mce-data-marked="1">As</span><span mce-data-marked="1"> NXException</span></div>
<div><span mce-data-marked="1"> ex.AssertErrorCode(</span><span mce-data-marked="1">1050029</span><span mce-data-marked="1">)</span></div>
<div><span mce-data-marked="1">End Try</span></div>
<br/>
<div><span mce-data-marked="1">Try</span></div>
<div><span mce-data-marked="1"> </span><span mce-data-marked="1">' 運算式仍然在使用中。</span></div>
<div><span mce-data-marked="1"> workPart.Expressions.Delete(expression6)</span></div>
<div><span mce-data-marked="1">Catch</span><span mce-data-marked="1"> ex </span><span mce-data-marked="1">As</span><span mce-data-marked="1"> NXException</span></div>
<div><span mce-data-marked="1"> ex.AssertErrorCode(</span><span mce-data-marked="1">1050029</span><span mce-data-marked="1">)</span></div>
<div><span mce-data-marked="1">End Try</span></div>
<br/>
<div><span mce-data-marked="1">Try</span></div>
<div><span mce-data-marked="1"> </span><span mce-data-marked="1">' 運算式仍然在使用中。</span></div>
<div><span mce-data-marked="1"> workPart.Expressions.Delete(expression8)</span></div>
<div><span mce-data-marked="1">Catch</span><span mce-data-marked="1"> ex </span><span mce-data-marked="1">As</span><span mce-data-marked="1"> NXException</span></div>
<div><span mce-data-marked="1"> ex.AssertErrorCode(</span><span mce-data-marked="1">1050029</span><span mce-data-marked="1">)</span></div>
<div><span mce-data-marked="1">End Try</span></div>
<br/>
<div><span mce-data-marked="1">Try</span></div>
<div><span mce-data-marked="1"> </span><span mce-data-marked="1">' 運算式仍然在使用中。</span></div>
<div><span mce-data-marked="1"> workPart.Expressions.Delete(expression10)</span></div>
<div><span mce-data-marked="1">Catch</span><span mce-data-marked="1"> ex </span><span mce-data-marked="1">As</span><span mce-data-marked="1"> NXException</span></div>
<div><span mce-data-marked="1"> ex.AssertErrorCode(</span><span mce-data-marked="1">1050029</span><span mce-data-marked="1">)</span></div>
<div><span mce-data-marked="1">End Try</span></div>
<br/>
<div><span mce-data-marked="1">Try</span></div>
<div><span mce-data-marked="1"> </span><span mce-data-marked="1">' 運算式仍然在使用中。</span></div>
<div><span mce-data-marked="1"> workPart.Expressions.Delete(expression3)</span></div>
<div><span mce-data-marked="1">Catch</span><span mce-data-marked="1"> ex </span><span mce-data-marked="1">As</span><span mce-data-marked="1"> NXException</span></div>
<div><span mce-data-marked="1"> ex.AssertErrorCode(</span><span mce-data-marked="1">1050029</span><span mce-data-marked="1">)</span></div>
<div><span mce-data-marked="1">End Try</span></div>
<br/>
<div><span mce-data-marked="1">plane2.DestroyPlane()</span></div>
<br/>
<div><span mce-data-marked="1">Try</span></div>
<div><span mce-data-marked="1"> </span><span mce-data-marked="1">' 運算式仍然在使用中。</span></div>
<div><span mce-data-marked="1"> workPart.Expressions.Delete(expression5)</span></div>
<div><span mce-data-marked="1">Catch</span><span mce-data-marked="1"> ex </span><span mce-data-marked="1">As</span><span mce-data-marked="1"> NXException</span></div>
<div><span mce-data-marked="1"> ex.AssertErrorCode(</span><span mce-data-marked="1">1050029</span><span mce-data-marked="1">)</span></div>
<div><span mce-data-marked="1">End Try</span></div>
<br/>
<div><span mce-data-marked="1">plane3.DestroyPlane()</span></div>
<br/>
<div><span mce-data-marked="1">Try</span></div>
<div><span mce-data-marked="1"> </span><span mce-data-marked="1">' 運算式仍然在使用中。</span></div>
<div><span mce-data-marked="1"> workPart.Expressions.Delete(expression7)</span></div>
<div><span mce-data-marked="1">Catch</span><span mce-data-marked="1"> ex </span><span mce-data-marked="1">As</span><span mce-data-marked="1"> NXException</span></div>
<div><span mce-data-marked="1"> ex.AssertErrorCode(</span><span mce-data-marked="1">1050029</span><span mce-data-marked="1">)</span></div>
<div><span mce-data-marked="1">End Try</span></div>
<br/>
<div><span mce-data-marked="1">plane4.DestroyPlane()</span></div>
<br/>
<div><span mce-data-marked="1">Try</span></div>
<div><span mce-data-marked="1"> </span><span mce-data-marked="1">' 運算式仍然在使用中。</span></div>
<div><span mce-data-marked="1"> workPart.Expressions.Delete(expression9)</span></div>
<div><span mce-data-marked="1">Catch</span><span mce-data-marked="1"> ex </span><span mce-data-marked="1">As</span><span mce-data-marked="1"> NXException</span></div>
<div><span mce-data-marked="1"> ex.AssertErrorCode(</span><span mce-data-marked="1">1050029</span><span mce-data-marked="1">)</span></div>
<div><span mce-data-marked="1">End Try</span></div>
<br/>
<div><span mce-data-marked="1">plane5.DestroyPlane()</span></div>
<br/>
<div><span mce-data-marked="1">datumCsysBuilder1.Csys = cartesianCoordinateSystem1</span></div>
<br/>
<div><span mce-data-marked="1">datumCsysBuilder1.DisplayScaleFactor = </span><span mce-data-marked="1">1.25</span></div>
<br/>
<div><span mce-data-marked="1">Dim</span><span mce-data-marked="1"> nXObject1 </span><span mce-data-marked="1">As</span><span mce-data-marked="1"> NXOpen.NXObject = </span><span mce-data-marked="1">Nothing</span></div>
<div><span mce-data-marked="1">nXObject1 = datumCsysBuilder1.Commit()</span></div>
<br/>
<div><span mce-data-marked="1">datumCsysBuilder1.Destroy()</span></div>
<br/>
<div><span mce-data-marked="1">Dim</span><span mce-data-marked="1"> markId5 </span><span mce-data-marked="1">As</span><span mce-data-marked="1"> NXOpen.Session.UndoMarkId = </span><span mce-data-marked="1">Nothing</span></div>
<div><span mce-data-marked="1">markId5 = theSession.SetUndoMark(NXOpen.Session.MarkVisibility.Visible, </span><span mce-data-marked="1">"起點"</span><span mce-data-marked="1">)</span></div>
<br/>
<div><span mce-data-marked="1">Dim</span><span mce-data-marked="1"> nullNXOpen_Sketch </span><span mce-data-marked="1">As</span><span mce-data-marked="1"> NXOpen.Sketch = </span><span mce-data-marked="1">Nothing</span></div>
<br/>
<div><span mce-data-marked="1">Dim</span><span mce-data-marked="1"> sketchInPlaceBuilder1 </span><span mce-data-marked="1">As</span><span mce-data-marked="1"> NXOpen.SketchInPlaceBuilder = </span><span mce-data-marked="1">Nothing</span></div>
<div><span mce-data-marked="1">sketchInPlaceBuilder1 = workPart.Sketches.CreateSketchInPlaceBuilder2(nullNXOpen_Sketch)</span></div>
<br/>
<div><span mce-data-marked="1">Dim</span><span mce-data-marked="1"> origin6 </span><span mce-data-marked="1">As</span><span mce-data-marked="1"> NXOpen.Point3d = </span><span mce-data-marked="1">New</span><span mce-data-marked="1"> NXOpen.Point3d(</span><span mce-data-marked="1">0.0</span><span mce-data-marked="1">, </span><span mce-data-marked="1">0.0</span><span mce-data-marked="1">, </span><span mce-data-marked="1">0.0</span><span mce-data-marked="1">)</span></div>
<div><span mce-data-marked="1">Dim</span><span mce-data-marked="1"> normal5 </span><span mce-data-marked="1">As</span><span mce-data-marked="1"> NXOpen.Vector3d = </span><span mce-data-marked="1">New</span><span mce-data-marked="1"> NXOpen.Vector3d(</span><span mce-data-marked="1">0.0</span><span mce-data-marked="1">, </span><span mce-data-marked="1">0.0</span><span mce-data-marked="1">, </span><span mce-data-marked="1">1.0</span><span mce-data-marked="1">)</span></div>
<div><span mce-data-marked="1">Dim</span><span mce-data-marked="1"> plane6 </span><span mce-data-marked="1">As</span><span mce-data-marked="1"> NXOpen.Plane = </span><span mce-data-marked="1">Nothing</span></div>
<div><span mce-data-marked="1">plane6 = workPart.Planes.CreatePlane(origin6, normal5, NXOpen.SmartObject.UpdateOption.WithinModeling)</span></div>
<br/>
<div><span mce-data-marked="1">sketchInPlaceBuilder1.PlaneReference = plane6</span></div>
<br/>
<div><span mce-data-marked="1">Dim</span><span mce-data-marked="1"> expression20 </span><span mce-data-marked="1">As</span><span mce-data-marked="1"> NXOpen.Expression = </span><span mce-data-marked="1">Nothing</span></div>
<div><span mce-data-marked="1">expression20 = workPart.Expressions.CreateSystemExpressionWithUnits(</span><span mce-data-marked="1">"0"</span><span mce-data-marked="1">, unit1)</span></div>
<br/>
<div><span mce-data-marked="1">Dim</span><span mce-data-marked="1"> expression21 </span><span mce-data-marked="1">As</span><span mce-data-marked="1"> NXOpen.Expression = </span><span mce-data-marked="1">Nothing</span></div>
<div><span mce-data-marked="1">expression21 = workPart.Expressions.CreateSystemExpressionWithUnits(</span><span mce-data-marked="1">"0"</span><span mce-data-marked="1">, unit1)</span></div>
<br/>
<div><span mce-data-marked="1">Dim</span><span mce-data-marked="1"> sketchAlongPathBuilder1 </span><span mce-data-marked="1">As</span><span mce-data-marked="1"> NXOpen.SketchAlongPathBuilder = </span><span mce-data-marked="1">Nothing</span></div>
<div><span mce-data-marked="1">sketchAlongPathBuilder1 = workPart.Sketches.CreateSketchAlongPathBuilder(nullNXOpen_Sketch)</span></div>
<br/>
<div><span mce-data-marked="1">theSession.SetUndoMarkName(markId5, </span><span mce-data-marked="1">"建立草圖 對話方塊"</span><span mce-data-marked="1">)</span></div>
<br/>
<div><span mce-data-marked="1">Dim</span><span mce-data-marked="1"> markId6 </span><span mce-data-marked="1">As</span><span mce-data-marked="1"> NXOpen.Session.UndoMarkId = </span><span mce-data-marked="1">Nothing</span></div>
<div><span mce-data-marked="1">markId6 = theSession.SetUndoMark(NXOpen.Session.MarkVisibility.Invisible, </span><span mce-data-marked="1">"建立草圖"</span><span mce-data-marked="1">)</span></div>
<br/>
<div><span mce-data-marked="1">theSession.DeleteUndoMark(markId6, </span><span mce-data-marked="1">Nothing</span><span mce-data-marked="1">)</span></div>
<br/>
<div><span mce-data-marked="1">Dim</span><span mce-data-marked="1"> markId7 </span><span mce-data-marked="1">As</span><span mce-data-marked="1"> NXOpen.Session.UndoMarkId = </span><span mce-data-marked="1">Nothing</span></div>
<div><span mce-data-marked="1">markId7 = theSession.SetUndoMark(NXOpen.Session.MarkVisibility.Invisible, </span><span mce-data-marked="1">"建立草圖"</span><span mce-data-marked="1">)</span></div>
<br/>
<div><span mce-data-marked="1">theSession.Preferences.Sketch.CreateInferredConstraints = </span><span mce-data-marked="1">True</span></div>
<br/>
<div><span mce-data-marked="1">theSession.Preferences.Sketch.ContinuousAutoDimensioning = </span><span mce-data-marked="1">True</span></div>
<br/>
<div><span mce-data-marked="1">theSession.Preferences.Sketch.DimensionLabel = NXOpen.Preferences.SketchPreferences.DimensionLabelType.Expression</span></div>
<br/>
<div><span mce-data-marked="1">theSession.Preferences.Sketch.TextSizeFixed = </span><span mce-data-marked="1">True</span></div>
<br/>
<div><span mce-data-marked="1">theSession.Preferences.Sketch.FixedTextSize = </span><span mce-data-marked="1">3.0</span></div>
<br/>
<div><span mce-data-marked="1">theSession.Preferences.Sketch.DisplayParenthesesOnReferenceDimensions = </span><span mce-data-marked="1">True</span></div>
<br/>
<div><span mce-data-marked="1">theSession.Preferences.Sketch.DisplayReferenceGeometry = </span><span mce-data-marked="1">False</span></div>
<br/>
<div><span mce-data-marked="1">theSession.Preferences.Sketch.ConstraintSymbolSize = </span><span mce-data-marked="1">3.0</span></div>
<br/>
<div><span mce-data-marked="1">theSession.Preferences.Sketch.DisplayObjectColor = </span><span mce-data-marked="1">False</span></div>
<br/>
<div><span mce-data-marked="1">theSession.Preferences.Sketch.DisplayObjectName = </span><span mce-data-marked="1">True</span></div>
<br/>
<div><span mce-data-marked="1">Dim</span><span mce-data-marked="1"> nXObject2 </span><span mce-data-marked="1">As</span><span mce-data-marked="1"> NXOpen.NXObject = </span><span mce-data-marked="1">Nothing</span></div>
<div><span mce-data-marked="1">nXObject2 = sketchInPlaceBuilder1.Commit()</span></div>
<br/>
<div><span mce-data-marked="1">Dim</span><span mce-data-marked="1"> sketch1 </span><span mce-data-marked="1">As</span><span mce-data-marked="1"> NXOpen.Sketch = </span><span mce-data-marked="1">CType</span><span mce-data-marked="1">(nXObject2, NXOpen.Sketch)</span></div>
<br/>
<div><span mce-data-marked="1">Dim</span><span mce-data-marked="1"> feature1 </span><span mce-data-marked="1">As</span><span mce-data-marked="1"> NXOpen.Features.Feature = </span><span mce-data-marked="1">Nothing</span></div>
<div><span mce-data-marked="1">feature1 = sketch1.Feature</span></div>
<br/>
<div><span mce-data-marked="1">Dim</span><span mce-data-marked="1"> markId8 </span><span mce-data-marked="1">As</span><span mce-data-marked="1"> NXOpen.Session.UndoMarkId = </span><span mce-data-marked="1">Nothing</span></div>
<div><span mce-data-marked="1">markId8 = theSession.SetUndoMark(NXOpen.Session.MarkVisibility.Invisible, </span><span mce-data-marked="1">"update"</span><span mce-data-marked="1">)</span></div>
<br/>
<div><span mce-data-marked="1">Dim</span><span mce-data-marked="1"> nErrs1 </span><span mce-data-marked="1">As</span><span mce-data-marked="1"> </span><span mce-data-marked="1">Integer</span><span mce-data-marked="1"> = </span><span mce-data-marked="1">Nothing</span></div>
<div><span mce-data-marked="1">nErrs1 = theSession.UpdateManager.DoUpdate(markId8)</span></div>
<br/>
<div><span mce-data-marked="1">sketch1.Activate(NXOpen.Sketch.ViewReorient.</span><span mce-data-marked="1">True</span><span mce-data-marked="1">)</span></div>
<br/>
<div><span mce-data-marked="1">theSession.DeleteUndoMark(markId7, </span><span mce-data-marked="1">Nothing</span><span mce-data-marked="1">)</span></div>
<br/>
<div><span mce-data-marked="1">theSession.SetUndoMarkName(markId5, </span><span mce-data-marked="1">"建立草圖"</span><span mce-data-marked="1">)</span></div>
<br/>
<div><span mce-data-marked="1">sketchInPlaceBuilder1.Destroy()</span></div>
<br/>
<div><span mce-data-marked="1">sketchAlongPathBuilder1.Destroy()</span></div>
<br/>
<div><span mce-data-marked="1">Try</span></div>
<div><span mce-data-marked="1"> </span><span mce-data-marked="1">' 運算式仍然在使用中。</span></div>
<div><span mce-data-marked="1"> workPart.Expressions.Delete(expression21)</span></div>
<div><span mce-data-marked="1">Catch</span><span mce-data-marked="1"> ex </span><span mce-data-marked="1">As</span><span mce-data-marked="1"> NXException</span></div>
<div><span mce-data-marked="1"> ex.AssertErrorCode(</span><span mce-data-marked="1">1050029</span><span mce-data-marked="1">)</span></div>
<div><span mce-data-marked="1">End Try</span></div>
<br/>
<div><span mce-data-marked="1">Try</span></div>
<div><span mce-data-marked="1"> </span><span mce-data-marked="1">' 運算式仍然在使用中。</span></div>
<div><span mce-data-marked="1"> workPart.Expressions.Delete(expression20)</span></div>
<div><span mce-data-marked="1">Catch</span><span mce-data-marked="1"> ex </span><span mce-data-marked="1">As</span><span mce-data-marked="1"> NXException</span></div>
<div><span mce-data-marked="1"> ex.AssertErrorCode(</span><span mce-data-marked="1">1050029</span><span mce-data-marked="1">)</span></div>
<div><span mce-data-marked="1">End Try</span></div>
<br/>
<div><span mce-data-marked="1">plane6.DestroyPlane()</span></div>
<br/>
<div><span mce-data-marked="1">Dim</span><span mce-data-marked="1"> scaleAboutPoint1 </span><span mce-data-marked="1">As</span><span mce-data-marked="1"> NXOpen.Point3d = </span><span mce-data-marked="1">New</span><span mce-data-marked="1"> NXOpen.Point3d(</span><span mce-data-marked="1">0.32929284143071819</span><span mce-data-marked="1">, -</span><span mce-data-marked="1">0.40832312337407828</span><span mce-data-marked="1">, </span><span mce-data-marked="1">0.0</span><span mce-data-marked="1">)</span></div>
<div><span mce-data-marked="1">Dim</span><span mce-data-marked="1"> viewCenter1 </span><span mce-data-marked="1">As</span><span mce-data-marked="1"> NXOpen.Point3d = </span><span mce-data-marked="1">New</span><span mce-data-marked="1"> NXOpen.Point3d(-</span><span mce-data-marked="1">0.3292928414306901</span><span mce-data-marked="1">, </span><span mce-data-marked="1">0.4083231233740659</span><span mce-data-marked="1">, </span><span mce-data-marked="1">0.0</span><span mce-data-marked="1">)</span></div>
<div><span mce-data-marked="1">workPart.ModelingViews.WorkView.ZoomAboutPoint(</span><span mce-data-marked="1">1.25</span><span mce-data-marked="1">, scaleAboutPoint1, viewCenter1)</span></div>
<br/>
<div><span mce-data-marked="1">Dim</span><span mce-data-marked="1"> scaleAboutPoint2 </span><span mce-data-marked="1">As</span><span mce-data-marked="1"> NXOpen.Point3d = </span><span mce-data-marked="1">New</span><span mce-data-marked="1"> NXOpen.Point3d(</span><span mce-data-marked="1">0.1159110801836211</span><span mce-data-marked="1">, -</span><span mce-data-marked="1">0.29504638592191679</span><span mce-data-marked="1">, </span><span mce-data-marked="1">0.0</span><span mce-data-marked="1">)</span></div>
<div><span mce-data-marked="1">Dim</span><span mce-data-marked="1"> viewCenter2 </span><span mce-data-marked="1">As</span><span mce-data-marked="1"> NXOpen.Point3d = </span><span mce-data-marked="1">New</span><span mce-data-marked="1"> NXOpen.Point3d(-</span><span mce-data-marked="1">0.11591108018359235</span><span mce-data-marked="1">, </span><span mce-data-marked="1">0.29504638592190419</span><span mce-data-marked="1">, </span><span mce-data-marked="1">0.0</span><span mce-data-marked="1">)</span></div>
<div><span mce-data-marked="1">workPart.ModelingViews.WorkView.ZoomAboutPoint(</span><span mce-data-marked="1">1.25</span><span mce-data-marked="1">, scaleAboutPoint2, viewCenter2)</span></div>
<br/>
<div><span mce-data-marked="1">Dim</span><span mce-data-marked="1"> scaleAboutPoint3 </span><span mce-data-marked="1">As</span><span mce-data-marked="1"> NXOpen.Point3d = </span><span mce-data-marked="1">New</span><span mce-data-marked="1"> NXOpen.Point3d(</span><span mce-data-marked="1">0.059009277184396122</span><span mce-data-marked="1">, -</span><span mce-data-marked="1">0.23603710873753417</span><span mce-data-marked="1">, </span><span mce-data-marked="1">0.0</span><span mce-data-marked="1">)</span></div>
<div><span mce-data-marked="1">Dim</span><span mce-data-marked="1"> viewCenter3 </span><span mce-data-marked="1">As</span><span mce-data-marked="1"> NXOpen.Point3d = </span><span mce-data-marked="1">New</span><span mce-data-marked="1"> NXOpen.Point3d(-</span><span mce-data-marked="1">0.059009277184367367</span><span mce-data-marked="1">, </span><span mce-data-marked="1">0.23603710873752196</span><span mce-data-marked="1">, </span><span mce-data-marked="1">0.0</span><span mce-data-marked="1">)</span></div>
<div><span mce-data-marked="1">workPart.ModelingViews.WorkView.ZoomAboutPoint(</span><span mce-data-marked="1">1.25</span><span mce-data-marked="1">, scaleAboutPoint3, viewCenter3)</span></div>
<br/>
<div><span mce-data-marked="1">Dim</span><span mce-data-marked="1"> scaleAboutPoint4 </span><span mce-data-marked="1">As</span><span mce-data-marked="1"> NXOpen.Point3d = </span><span mce-data-marked="1">New</span><span mce-data-marked="1"> NXOpen.Point3d(</span><span mce-data-marked="1">0.047207421747519185</span><span mce-data-marked="1">, -</span><span mce-data-marked="1">0.18882968699002903</span><span mce-data-marked="1">, </span><span mce-data-marked="1">0.0</span><span mce-data-marked="1">)</span></div>
<div><span mce-data-marked="1">Dim</span><span mce-data-marked="1"> viewCenter4 </span><span mce-data-marked="1">As</span><span mce-data-marked="1"> NXOpen.Point3d = </span><span mce-data-marked="1">New</span><span mce-data-marked="1"> NXOpen.Point3d(-</span><span mce-data-marked="1">0.047207421747490437</span><span mce-data-marked="1">, </span><span mce-data-marked="1">0.18882968699001637</span><span mce-data-marked="1">, </span><span mce-data-marked="1">0.0</span><span mce-data-marked="1">)</span></div>
<div><span mce-data-marked="1">workPart.ModelingViews.WorkView.ZoomAboutPoint(</span><span mce-data-marked="1">0.80000000000000004</span><span mce-data-marked="1">, scaleAboutPoint4, viewCenter4)</span></div>
<br/>
<div><span mce-data-marked="1">Dim</span><span mce-data-marked="1"> scaleAboutPoint5 </span><span mce-data-marked="1">As</span><span mce-data-marked="1"> NXOpen.Point3d = </span><span mce-data-marked="1">New</span><span mce-data-marked="1"> NXOpen.Point3d(</span><span mce-data-marked="1">0.059009277184396101</span><span mce-data-marked="1">, -</span><span mce-data-marked="1">0.23603710873753411</span><span mce-data-marked="1">, </span><span mce-data-marked="1">0.0</span><span mce-data-marked="1">)</span></div>
<div><span mce-data-marked="1">Dim</span><span mce-data-marked="1"> viewCenter5 </span><span mce-data-marked="1">As</span><span mce-data-marked="1"> NXOpen.Point3d = </span><span mce-data-marked="1">New</span><span mce-data-marked="1"> NXOpen.Point3d(-</span><span mce-data-marked="1">0.059009277184367354</span><span mce-data-marked="1">, </span><span mce-data-marked="1">0.23603710873752259</span><span mce-data-marked="1">, </span><span mce-data-marked="1">0.0</span><span mce-data-marked="1">)</span></div>
<div><span mce-data-marked="1">workPart.ModelingViews.WorkView.ZoomAboutPoint(</span><span mce-data-marked="1">0.80000000000000004</span><span mce-data-marked="1">, scaleAboutPoint5, viewCenter5)</span></div>
<br/>
<div><span mce-data-marked="1">Dim</span><span mce-data-marked="1"> scaleAboutPoint6 </span><span mce-data-marked="1">As</span><span mce-data-marked="1"> NXOpen.Point3d = </span><span mce-data-marked="1">New</span><span mce-data-marked="1"> NXOpen.Point3d(</span><span mce-data-marked="1">0.073761596480491534</span><span mce-data-marked="1">, -</span><span mce-data-marked="1">0.29504638592191579</span><span mce-data-marked="1">, </span><span mce-data-marked="1">0.0</span><span mce-data-marked="1">)</span></div>
<div><span mce-data-marked="1">Dim</span><span mce-data-marked="1"> viewCenter6 </span><span mce-data-marked="1">As</span><span mce-data-marked="1"> NXOpen.Point3d = </span><span mce-data-marked="1">New</span><span mce-data-marked="1"> NXOpen.Point3d(-</span><span mce-data-marked="1">0.073761596480462779</span><span mce-data-marked="1">, </span><span mce-data-marked="1">0.29504638592190413</span><span mce-data-marked="1">, </span><span mce-data-marked="1">0.0</span><span mce-data-marked="1">)</span></div>
<div><span mce-data-marked="1">workPart.ModelingViews.WorkView.ZoomAboutPoint(</span><span mce-data-marked="1">0.80000000000000004</span><span mce-data-marked="1">, scaleAboutPoint6, viewCenter6)</span></div>
<br/>
<div><span mce-data-marked="1">Dim</span><span mce-data-marked="1"> scaleAboutPoint7 </span><span mce-data-marked="1">As</span><span mce-data-marked="1"> NXOpen.Point3d = </span><span mce-data-marked="1">New</span><span mce-data-marked="1"> NXOpen.Point3d(</span><span mce-data-marked="1">0.092201995600609918</span><span mce-data-marked="1">, -</span><span mce-data-marked="1">0.3688079824023936</span><span mce-data-marked="1">, </span><span mce-data-marked="1">0.0</span><span mce-data-marked="1">)</span></div>
<div><span mce-data-marked="1">Dim</span><span mce-data-marked="1"> viewCenter7 </span><span mce-data-marked="1">As</span><span mce-data-marked="1"> NXOpen.Point3d = </span><span mce-data-marked="1">New</span><span mce-data-marked="1"> NXOpen.Point3d(-</span><span mce-data-marked="1">0.092201995600580719</span><span mce-data-marked="1">, </span><span mce-data-marked="1">0.36880798240238238</span><span mce-data-marked="1">, </span><span mce-data-marked="1">0.0</span><span mce-data-marked="1">)</span></div>
<div><span mce-data-marked="1">workPart.ModelingViews.WorkView.ZoomAboutPoint(</span><span mce-data-marked="1">0.80000000000000004</span><span mce-data-marked="1">, scaleAboutPoint7, viewCenter7)</span></div>
<br/>
<div><span mce-data-marked="1">Dim</span><span mce-data-marked="1"> scaleAboutPoint8 </span><span mce-data-marked="1">As</span><span mce-data-marked="1"> NXOpen.Point3d = </span><span mce-data-marked="1">New</span><span mce-data-marked="1"> NXOpen.Point3d(</span><span mce-data-marked="1">0.18111106278689948</span><span mce-data-marked="1">, -</span><span mce-data-marked="1">0.32929284143070936</span><span mce-data-marked="1">, </span><span mce-data-marked="1">0.0</span><span mce-data-marked="1">)</span></div>
<div><span mce-data-marked="1">Dim</span><span mce-data-marked="1"> viewCenter8 </span><span mce-data-marked="1">As</span><span mce-data-marked="1"> NXOpen.Point3d = </span><span mce-data-marked="1">New</span><span mce-data-marked="1"> NXOpen.Point3d(-</span><span mce-data-marked="1">0.18111106278687139</span><span mce-data-marked="1">, </span><span mce-data-marked="1">0.32929284143069809</span><span mce-data-marked="1">, </span><span mce-data-marked="1">0.0</span><span mce-data-marked="1">)</span></div>
<div><span mce-data-marked="1">workPart.ModelingViews.WorkView.ZoomAboutPoint(</span><span mce-data-marked="1">1.25</span><span mce-data-marked="1">, scaleAboutPoint8, viewCenter8)</span></div>
<br/>
<div><span mce-data-marked="1">' ----------------------------------------------</span></div>
<div><span mce-data-marked="1">' 功能表：插入(S)-&gt;草圖曲線(S)-&gt;圓(C)...</span></div>
<div><span mce-data-marked="1">' ----------------------------------------------</span></div>
<div><span mce-data-marked="1">Dim</span><span mce-data-marked="1"> markId9 </span><span mce-data-marked="1">As</span><span mce-data-marked="1"> NXOpen.Session.UndoMarkId = </span><span mce-data-marked="1">Nothing</span></div>
<div><span mce-data-marked="1">markId9 = theSession.SetUndoMark(NXOpen.Session.MarkVisibility.Invisible, </span><span mce-data-marked="1">"Profile short list"</span><span mce-data-marked="1">)</span></div>
<br/>
<div><span mce-data-marked="1">Dim</span><span mce-data-marked="1"> markId10 </span><span mce-data-marked="1">As</span><span mce-data-marked="1"> NXOpen.Session.UndoMarkId = </span><span mce-data-marked="1">Nothing</span></div>
<div><span mce-data-marked="1">markId10 = theSession.SetUndoMark(NXOpen.Session.MarkVisibility.Invisible, </span><span mce-data-marked="1">"Curve"</span><span mce-data-marked="1">)</span></div>
<br/>
<div><span mce-data-marked="1">Dim</span><span mce-data-marked="1"> expression22 </span><span mce-data-marked="1">As</span><span mce-data-marked="1"> NXOpen.Expression = </span><span mce-data-marked="1">Nothing</span></div>
<div><span mce-data-marked="1">expression22 = workPart.Expressions.CreateSystemExpression(</span><span mce-data-marked="1">"2.8"</span><span mce-data-marked="1">)</span></div>
<br/>
<div><span mce-data-marked="1">theSession.SetUndoMarkVisibility(markId10, </span><span mce-data-marked="1">"Curve"</span><span mce-data-marked="1">, NXOpen.Session.MarkVisibility.Visible)</span></div>
<br/>
<div><span mce-data-marked="1">Dim</span><span mce-data-marked="1"> nXMatrix1 </span><span mce-data-marked="1">As</span><span mce-data-marked="1"> NXOpen.NXMatrix = </span><span mce-data-marked="1">Nothing</span></div>
<div><span mce-data-marked="1">nXMatrix1 = theSession.ActiveSketch.Orientation</span></div>
<br/>
<div><span mce-data-marked="1">Dim</span><span mce-data-marked="1"> center1 </span><span mce-data-marked="1">As</span><span mce-data-marked="1"> NXOpen.Point3d = </span><span mce-data-marked="1">New</span><span mce-data-marked="1"> NXOpen.Point3d(</span><span mce-data-marked="1">0.0</span><span mce-data-marked="1">, </span><span mce-data-marked="1">0.0</span><span mce-data-marked="1">, </span><span mce-data-marked="1">0.0</span><span mce-data-marked="1">)</span></div>
<div><span mce-data-marked="1">Dim</span><span mce-data-marked="1"> arc1 </span><span mce-data-marked="1">As</span><span mce-data-marked="1"> NXOpen.Arc = </span><span mce-data-marked="1">Nothing</span></div>
<div><span mce-data-marked="1">arc1 = workPart.Curves.CreateArc(center1, nXMatrix1, </span><span mce-data-marked="1">1.3999999999999999</span><span mce-data-marked="1">, </span><span mce-data-marked="1">0.0</span><span mce-data-marked="1">, ( </span><span mce-data-marked="1">360.0</span><span mce-data-marked="1"> * Math.Pi/</span><span mce-data-marked="1">180.0</span><span mce-data-marked="1"> ))</span></div>
<br/>
<div><span mce-data-marked="1">theSession.ActiveSketch.AddGeometry(arc1, NXOpen.Sketch.InferConstraintsOption.InferNoConstraints)</span></div>
<br/>
<div><span mce-data-marked="1">Dim</span><span mce-data-marked="1"> geom1_1 </span><span mce-data-marked="1">As</span><span mce-data-marked="1"> NXOpen.Sketch.ConstraintGeometry = </span><span mce-data-marked="1">Nothing</span></div>
<div><span mce-data-marked="1">geom1_1.Geometry = arc1</span></div>
<div><span mce-data-marked="1">geom1_1.PointType = NXOpen.Sketch.ConstraintPointType.ArcCenter</span></div>
<div><span mce-data-marked="1">geom1_1.SplineDefiningPointIndex = </span><span mce-data-marked="1">0</span></div>
<div><span mce-data-marked="1">Dim</span><span mce-data-marked="1"> geom2_1 </span><span mce-data-marked="1">As</span><span mce-data-marked="1"> NXOpen.Sketch.ConstraintGeometry = </span><span mce-data-marked="1">Nothing</span></div>
<div><span mce-data-marked="1">Dim</span><span mce-data-marked="1"> datumCsys1 </span><span mce-data-marked="1">As</span><span mce-data-marked="1"> NXOpen.Features.DatumCsys = </span><span mce-data-marked="1">CType</span><span mce-data-marked="1">(workPart.Features.FindObject(</span><span mce-data-marked="1">"SKETCH(1:1B)"</span><span mce-data-marked="1">), NXOpen.Features.DatumCsys)</span></div>
<br/>
<div><span mce-data-marked="1">Dim</span><span mce-data-marked="1"> point2 </span><span mce-data-marked="1">As</span><span mce-data-marked="1"> NXOpen.Point = </span><span mce-data-marked="1">CType</span><span mce-data-marked="1">(datumCsys1.FindObject(</span><span mce-data-marked="1">"POINT 1"</span><span mce-data-marked="1">), NXOpen.Point)</span></div>
<br/>
<div><span mce-data-marked="1">geom2_1.Geometry = point2</span></div>
<div><span mce-data-marked="1">geom2_1.PointType = NXOpen.Sketch.ConstraintPointType.None</span></div>
<div><span mce-data-marked="1">geom2_1.SplineDefiningPointIndex = </span><span mce-data-marked="1">0</span></div>
<div><span mce-data-marked="1">Dim</span><span mce-data-marked="1"> sketchGeometricConstraint1 </span><span mce-data-marked="1">As</span><span mce-data-marked="1"> NXOpen.SketchGeometricConstraint = </span><span mce-data-marked="1">Nothing</span></div>
<div><span mce-data-marked="1">sketchGeometricConstraint1 = theSession.ActiveSketch.CreateCoincidentConstraint(geom1_1, geom2_1)</span></div>
<br/>
<div><span mce-data-marked="1">Dim</span><span mce-data-marked="1"> dimObject1_1 </span><span mce-data-marked="1">As</span><span mce-data-marked="1"> NXOpen.Sketch.DimensionGeometry = </span><span mce-data-marked="1">Nothing</span></div>
<div><span mce-data-marked="1">dimObject1_1.Geometry = arc1</span></div>
<div><span mce-data-marked="1">dimObject1_1.AssocType = NXOpen.Sketch.AssocType.None</span></div>
<div><span mce-data-marked="1">dimObject1_1.AssocValue = </span><span mce-data-marked="1">0</span></div>
<div><span mce-data-marked="1">dimObject1_1.HelpPoint.X = </span><span mce-data-marked="1">0.0</span></div>
<div><span mce-data-marked="1">dimObject1_1.HelpPoint.Y = </span><span mce-data-marked="1">0.0</span></div>
<div><span mce-data-marked="1">dimObject1_1.HelpPoint.Z = </span><span mce-data-marked="1">0.0</span></div>
<div><span mce-data-marked="1">Dim</span><span mce-data-marked="1"> nullNXOpen_NXObject </span><span mce-data-marked="1">As</span><span mce-data-marked="1"> NXOpen.NXObject = </span><span mce-data-marked="1">Nothing</span></div>
<br/>
<div><span mce-data-marked="1">dimObject1_1.View = nullNXOpen_NXObject</span></div>
<div><span mce-data-marked="1">Dim</span><span mce-data-marked="1"> dimOrigin1 </span><span mce-data-marked="1">As</span><span mce-data-marked="1"> NXOpen.Point3d = </span><span mce-data-marked="1">New</span><span mce-data-marked="1"> NXOpen.Point3d(</span><span mce-data-marked="1">0.0</span><span mce-data-marked="1">, </span><span mce-data-marked="1">0.14934856430242965</span><span mce-data-marked="1">, </span><span mce-data-marked="1">0.0</span><span mce-data-marked="1">)</span></div>
<div><span mce-data-marked="1">Dim</span><span mce-data-marked="1"> sketchDimensionalConstraint1 </span><span mce-data-marked="1">As</span><span mce-data-marked="1"> NXOpen.SketchDimensionalConstraint = </span><span mce-data-marked="1">Nothing</span></div>
<div><span mce-data-marked="1">sketchDimensionalConstraint1 = theSession.ActiveSketch.CreateDiameterDimension(dimObject1_1, dimOrigin1, expression22, NXOpen.Sketch.DimensionOption.CreateAsDriving)</span></div>
<br/>
<div><span mce-data-marked="1">Dim</span><span mce-data-marked="1"> dimension1 </span><span mce-data-marked="1">As</span><span mce-data-marked="1"> NXOpen.Annotations.Dimension = </span><span mce-data-marked="1">Nothing</span></div>
<div><span mce-data-marked="1">dimension1 = sketchDimensionalConstraint1.AssociatedDimension</span></div>
<br/>
<div><span mce-data-marked="1">theSession.ActiveSketch.Update()</span></div>
<br/>
<div><span mce-data-marked="1">Dim</span><span mce-data-marked="1"> markId11 </span><span mce-data-marked="1">As</span><span mce-data-marked="1"> NXOpen.Session.UndoMarkId = </span><span mce-data-marked="1">Nothing</span></div>
<div><span mce-data-marked="1">markId11 = theSession.SetUndoMark(NXOpen.Session.MarkVisibility.Invisible, </span><span mce-data-marked="1">"Curve"</span><span mce-data-marked="1">)</span></div>
<br/>
<div><span mce-data-marked="1">' ----------------------------------------------</span></div>
<div><span mce-data-marked="1">' 功能表：渲染樣式(D)-&gt;藝術外觀(T)</span></div>
<div><span mce-data-marked="1">' ----------------------------------------------</span></div>
<div><span mce-data-marked="1">Dim</span><span mce-data-marked="1"> nullNXOpen_Display_TrueStudio </span><span mce-data-marked="1">As</span><span mce-data-marked="1"> NXOpen.Display.TrueStudio = </span><span mce-data-marked="1">Nothing</span></div>
<br/>
<div><span mce-data-marked="1">Dim</span><span mce-data-marked="1"> trueStudioBuilder1 </span><span mce-data-marked="1">As</span><span mce-data-marked="1"> NXOpen.Display.TrueStudioBuilder = </span><span mce-data-marked="1">Nothing</span></div>
<div><span mce-data-marked="1">trueStudioBuilder1 = workPart.TrueStudioObjs.CreateTrueStudioBuilder(nullNXOpen_Display_TrueStudio)</span></div>
<br/>
<div><span mce-data-marked="1">trueStudioBuilder1.ModeToggle = </span><span mce-data-marked="1">True</span></div>
<br/>
<div><span mce-data-marked="1">workPart.ModelingViews.WorkView.RenderingStyle = NXOpen.View.RenderingStyleType.Studio</span></div>
<br/>
<div><span mce-data-marked="1">Dim</span><span mce-data-marked="1"> nXObject3 </span><span mce-data-marked="1">As</span><span mce-data-marked="1"> NXOpen.NXObject = </span><span mce-data-marked="1">Nothing</span></div>
<div><span mce-data-marked="1">nXObject3 = trueStudioBuilder1.Commit()</span></div>
<br/>
<div><span mce-data-marked="1">trueStudioBuilder1.Destroy()</span></div>
<br/>
<div><span mce-data-marked="1">workPart.ModelingViews.WorkView.RenderingStyle = NXOpen.View.RenderingStyleType.Studio</span></div>
<br/>
<div><span mce-data-marked="1">' ----------------------------------------------</span></div>
<div><span mce-data-marked="1">' 功能表：檔案(F)-&gt;完成草圖(K)</span></div>
<div><span mce-data-marked="1">' ----------------------------------------------</span></div>
<div><span mce-data-marked="1">theSession.DeleteUndoMark(markId11, </span><span mce-data-marked="1">"Curve"</span><span mce-data-marked="1">)</span></div>
<br/>
<div><span mce-data-marked="1">Dim</span><span mce-data-marked="1"> sketch2 </span><span mce-data-marked="1">As</span><span mce-data-marked="1"> NXOpen.Sketch = </span><span mce-data-marked="1">Nothing</span></div>
<div><span mce-data-marked="1">sketch2 = theSession.ActiveSketch</span></div>
<br/>
<div><span mce-data-marked="1">Dim</span><span mce-data-marked="1"> markId12 </span><span mce-data-marked="1">As</span><span mce-data-marked="1"> NXOpen.Session.UndoMarkId = </span><span mce-data-marked="1">Nothing</span></div>
<div><span mce-data-marked="1">markId12 = theSession.SetUndoMark(NXOpen.Session.MarkVisibility.Invisible, </span><span mce-data-marked="1">"Deactivate Sketch"</span><span mce-data-marked="1">)</span></div>
<br/>
<div><span mce-data-marked="1">theSession.ActiveSketch.Deactivate(NXOpen.Sketch.ViewReorient.</span><span mce-data-marked="1">True</span><span mce-data-marked="1">, NXOpen.Sketch.UpdateLevel.Model)</span></div>
<br/>
<div><span mce-data-marked="1">' ----------------------------------------------</span></div>
<div><span mce-data-marked="1">' 功能表：插入(S)-&gt;設計特徵(E)-&gt;拉伸(X)...</span></div>
<div><span mce-data-marked="1">' ----------------------------------------------</span></div>
<div><span mce-data-marked="1">Dim</span><span mce-data-marked="1"> markId13 </span><span mce-data-marked="1">As</span><span mce-data-marked="1"> NXOpen.Session.UndoMarkId = </span><span mce-data-marked="1">Nothing</span></div>
<div><span mce-data-marked="1">markId13 = theSession.SetUndoMark(NXOpen.Session.MarkVisibility.Visible, </span><span mce-data-marked="1">"起點"</span><span mce-data-marked="1">)</span></div>
<br/>
<div><span mce-data-marked="1">Dim</span><span mce-data-marked="1"> extrudeBuilder1 </span><span mce-data-marked="1">As</span><span mce-data-marked="1"> NXOpen.Features.ExtrudeBuilder = </span><span mce-data-marked="1">Nothing</span></div>
<div><span mce-data-marked="1">extrudeBuilder1 = workPart.Features.CreateExtrudeBuilder(nullNXOpen_Features_Feature)</span></div>
<br/>
<div><span mce-data-marked="1">Dim</span><span mce-data-marked="1"> section1 </span><span mce-data-marked="1">As</span><span mce-data-marked="1"> NXOpen.Section = </span><span mce-data-marked="1">Nothing</span></div>
<div><span mce-data-marked="1">section1 = workPart.Sections.CreateSection(</span><span mce-data-marked="1">0.0094999999999999998</span><span mce-data-marked="1">, </span><span mce-data-marked="1">0.01</span><span mce-data-marked="1">, </span><span mce-data-marked="1">0.5</span><span mce-data-marked="1">)</span></div>
<br/>
<div><span mce-data-marked="1">extrudeBuilder1.Section = section1</span></div>
<br/>
<div><span mce-data-marked="1">extrudeBuilder1.AllowSelfIntersectingSection(</span><span mce-data-marked="1">True</span><span mce-data-marked="1">)</span></div>
<br/>
<div><span mce-data-marked="1">Dim</span><span mce-data-marked="1"> expression23 </span><span mce-data-marked="1">As</span><span mce-data-marked="1"> NXOpen.Expression = </span><span mce-data-marked="1">Nothing</span></div>
<div><span mce-data-marked="1">expression23 = workPart.Expressions.CreateSystemExpressionWithUnits(</span><span mce-data-marked="1">"2.00"</span><span mce-data-marked="1">, unit2)</span></div>
<br/>
<div><span mce-data-marked="1">extrudeBuilder1.DistanceTolerance = </span><span mce-data-marked="1">0.01</span></div>
<br/>
<div><span mce-data-marked="1">extrudeBuilder1.BooleanOperation.Type = NXOpen.GeometricUtilities.BooleanOperation.BooleanType.Create</span></div>
<br/>
<div><span mce-data-marked="1">Dim</span><span mce-data-marked="1"> targetBodies1(</span><span mce-data-marked="1">0</span><span mce-data-marked="1">) </span><span mce-data-marked="1">As</span><span mce-data-marked="1"> NXOpen.Body</span></div>
<div><span mce-data-marked="1">Dim</span><span mce-data-marked="1"> nullNXOpen_Body </span><span mce-data-marked="1">As</span><span mce-data-marked="1"> NXOpen.Body = </span><span mce-data-marked="1">Nothing</span></div>
<br/>
<div><span mce-data-marked="1">targetBodies1(</span><span mce-data-marked="1">0</span><span mce-data-marked="1">) = nullNXOpen_Body</span></div>
<div><span mce-data-marked="1">extrudeBuilder1.BooleanOperation.SetTargetBodies(targetBodies1)</span></div>
<br/>
<div><span mce-data-marked="1">extrudeBuilder1.Limits.StartExtend.Value.SetFormula(</span><span mce-data-marked="1">"0"</span><span mce-data-marked="1">)</span></div>
<br/>
<div><span mce-data-marked="1">extrudeBuilder1.Limits.EndExtend.Value.SetFormula(</span><span mce-data-marked="1">"25"</span><span mce-data-marked="1">)</span></div>
<br/>
<div><span mce-data-marked="1">extrudeBuilder1.Offset.StartOffset.SetFormula(</span><span mce-data-marked="1">"0"</span><span mce-data-marked="1">)</span></div>
<br/>
<div><span mce-data-marked="1">extrudeBuilder1.Offset.EndOffset.SetFormula(</span><span mce-data-marked="1">"5"</span><span mce-data-marked="1">)</span></div>
<br/>
<div><span mce-data-marked="1">Dim</span><span mce-data-marked="1"> smartVolumeProfileBuilder1 </span><span mce-data-marked="1">As</span><span mce-data-marked="1"> NXOpen.GeometricUtilities.SmartVolumeProfileBuilder = </span><span mce-data-marked="1">Nothing</span></div>
<div><span mce-data-marked="1">smartVolumeProfileBuilder1 = extrudeBuilder1.SmartVolumeProfile</span></div>
<br/>
<div><span mce-data-marked="1">smartVolumeProfileBuilder1.OpenProfileSmartVolumeOption = </span><span mce-data-marked="1">False</span></div>
<br/>
<div><span mce-data-marked="1">smartVolumeProfileBuilder1.CloseProfileRule = NXOpen.GeometricUtilities.SmartVolumeProfileBuilder.CloseProfileRuleType.Fci</span></div>
<br/>
<div><span mce-data-marked="1">theSession.SetUndoMarkName(markId13, </span><span mce-data-marked="1">"拉伸 對話方塊"</span><span mce-data-marked="1">)</span></div>
<br/>
<div><span mce-data-marked="1">extrudeBuilder1.Limits.StartExtend.Value.SetFormula(</span><span mce-data-marked="1">"0"</span><span mce-data-marked="1">)</span></div>
<br/>
<div><span mce-data-marked="1">extrudeBuilder1.Limits.EndExtend.Value.SetFormula(</span><span mce-data-marked="1">"25"</span><span mce-data-marked="1">)</span></div>
<br/>
<div><span mce-data-marked="1">extrudeBuilder1.Draft.FrontDraftAngle.SetFormula(</span><span mce-data-marked="1">"2"</span><span mce-data-marked="1">)</span></div>
<br/>
<div><span mce-data-marked="1">extrudeBuilder1.Draft.BackDraftAngle.SetFormula(</span><span mce-data-marked="1">"2"</span><span mce-data-marked="1">)</span></div>
<br/>
<div><span mce-data-marked="1">extrudeBuilder1.Offset.StartOffset.SetFormula(</span><span mce-data-marked="1">"0"</span><span mce-data-marked="1">)</span></div>
<br/>
<div><span mce-data-marked="1">extrudeBuilder1.Offset.EndOffset.SetFormula(</span><span mce-data-marked="1">"5"</span><span mce-data-marked="1">)</span></div>
<br/>
<div><span mce-data-marked="1">section1.DistanceTolerance = </span><span mce-data-marked="1">0.01</span></div>
<br/>
<div><span mce-data-marked="1">section1.ChainingTolerance = </span><span mce-data-marked="1">0.0094999999999999998</span></div>
<br/>
<div><span mce-data-marked="1">section1.SetAllowedEntityTypes(NXOpen.Section.AllowTypes.OnlyCurves)</span></div>
<br/>
<div><span mce-data-marked="1">Dim</span><span mce-data-marked="1"> markId14 </span><span mce-data-marked="1">As</span><span mce-data-marked="1"> NXOpen.Session.UndoMarkId = </span><span mce-data-marked="1">Nothing</span></div>
<div><span mce-data-marked="1">markId14 = theSession.SetUndoMark(NXOpen.Session.MarkVisibility.Invisible, </span><span mce-data-marked="1">"section mark"</span><span mce-data-marked="1">)</span></div>
<br/>
<div><span mce-data-marked="1">Dim</span><span mce-data-marked="1"> markId15 </span><span mce-data-marked="1">As</span><span mce-data-marked="1"> NXOpen.Session.UndoMarkId = </span><span mce-data-marked="1">Nothing</span></div>
<div><span mce-data-marked="1">markId15 = theSession.SetUndoMark(NXOpen.Session.MarkVisibility.Invisible, </span><span mce-data-marked="1">Nothing</span><span mce-data-marked="1">)</span></div>
<br/>
<div><span mce-data-marked="1">Dim</span><span mce-data-marked="1"> features1(</span><span mce-data-marked="1">0</span><span mce-data-marked="1">) </span><span mce-data-marked="1">As</span><span mce-data-marked="1"> NXOpen.Features.Feature</span></div>
<div><span mce-data-marked="1">Dim</span><span mce-data-marked="1"> sketchFeature1 </span><span mce-data-marked="1">As</span><span mce-data-marked="1"> NXOpen.Features.SketchFeature = </span><span mce-data-marked="1">CType</span><span mce-data-marked="1">(feature1, NXOpen.Features.SketchFeature)</span></div>
<br/>
<div><span mce-data-marked="1">features1(</span><span mce-data-marked="1">0</span><span mce-data-marked="1">) = sketchFeature1</span></div>
<div><span mce-data-marked="1">Dim</span><span mce-data-marked="1"> curveFeatureRule1 </span><span mce-data-marked="1">As</span><span mce-data-marked="1"> NXOpen.CurveFeatureRule = </span><span mce-data-marked="1">Nothing</span></div>
<div><span mce-data-marked="1">curveFeatureRule1 = workPart.ScRuleFactory.CreateRuleCurveFeature(features1)</span></div>
<br/>
<div><span mce-data-marked="1">section1.AllowSelfIntersection(</span><span mce-data-marked="1">True</span><span mce-data-marked="1">)</span></div>
<br/>
<div><span mce-data-marked="1">Dim</span><span mce-data-marked="1"> rules1(</span><span mce-data-marked="1">0</span><span mce-data-marked="1">) </span><span mce-data-marked="1">As</span><span mce-data-marked="1"> NXOpen.SelectionIntentRule</span></div>
<div><span mce-data-marked="1">rules1(</span><span mce-data-marked="1">0</span><span mce-data-marked="1">) = curveFeatureRule1</span></div>
<div><span mce-data-marked="1">Dim</span><span mce-data-marked="1"> helpPoint1 </span><span mce-data-marked="1">As</span><span mce-data-marked="1"> NXOpen.Point3d = </span><span mce-data-marked="1">New</span><span mce-data-marked="1"> NXOpen.Point3d(-</span><span mce-data-marked="1">1.3642199176742373</span><span mce-data-marked="1">, -</span><span mce-data-marked="1">0.31143699864209995</span><span mce-data-marked="1">, </span><span mce-data-marked="1">0.0</span><span mce-data-marked="1">)</span></div>
<div><span mce-data-marked="1">section1.AddToSection(rules1, arc1, nullNXOpen_NXObject, nullNXOpen_NXObject, helpPoint1, NXOpen.Section.Mode.Create, </span><span mce-data-marked="1">False</span><span mce-data-marked="1">)</span></div>
<br/>
<div><span mce-data-marked="1">theSession.DeleteUndoMark(markId15, </span><span mce-data-marked="1">Nothing</span><span mce-data-marked="1">)</span></div>
<br/>
<div><span mce-data-marked="1">Dim</span><span mce-data-marked="1"> direction1 </span><span mce-data-marked="1">As</span><span mce-data-marked="1"> NXOpen.Direction = </span><span mce-data-marked="1">Nothing</span></div>
<div><span mce-data-marked="1">direction1 = workPart.Directions.CreateDirection(sketch2, NXOpen.Sense.Forward, NXOpen.SmartObject.UpdateOption.WithinModeling)</span></div>
<br/>
<div><span mce-data-marked="1">extrudeBuilder1.Direction = direction1</span></div>
<br/>
<div><span mce-data-marked="1">Dim</span><span mce-data-marked="1"> expression24 </span><span mce-data-marked="1">As</span><span mce-data-marked="1"> NXOpen.Expression = </span><span mce-data-marked="1">Nothing</span></div>
<div><span mce-data-marked="1">expression24 = workPart.Expressions.CreateSystemExpressionWithUnits(</span><span mce-data-marked="1">"0"</span><span mce-data-marked="1">, unit1)</span></div>
<br/>
<div><span mce-data-marked="1">theSession.DeleteUndoMark(markId14, </span><span mce-data-marked="1">Nothing</span><span mce-data-marked="1">)</span></div>
<br/>
<div><span mce-data-marked="1">extrudeBuilder1.Limits.EndExtend.Value.SetFormula(</span><span mce-data-marked="1">"6"</span><span mce-data-marked="1">)</span></div>
<br/>
<div><span mce-data-marked="1">Dim</span><span mce-data-marked="1"> rotMatrix1 </span><span mce-data-marked="1">As</span><span mce-data-marked="1"> NXOpen.Matrix3x3 = </span><span mce-data-marked="1">Nothing</span></div>
<div><span mce-data-marked="1">rotMatrix1.Xx = </span><span mce-data-marked="1">0.34117009820603067</span></div>
<div><span mce-data-marked="1">rotMatrix1.Xy = </span><span mce-data-marked="1">0.93771583394525115</span></div>
<div><span mce-data-marked="1">rotMatrix1.Xz = </span><span mce-data-marked="1">0.065513196063442206</span></div>
<div><span mce-data-marked="1">rotMatrix1.Yx = -</span><span mce-data-marked="1">0.65255317952837755</span></div>
<div><span mce-data-marked="1">rotMatrix1.Yy = </span><span mce-data-marked="1">0.18610108969583089</span></div>
<div><span mce-data-marked="1">rotMatrix1.Yz = </span><span mce-data-marked="1">0.734534364275374</span></div>
<div><span mce-data-marked="1">rotMatrix1.Zx = </span><span mce-data-marked="1">0.67659242678106424</span></div>
<div><span mce-data-marked="1">rotMatrix1.Zy = -</span><span mce-data-marked="1">0.29335200558779939</span></div>
<div><span mce-data-marked="1">rotMatrix1.Zz = </span><span mce-data-marked="1">0.67540157598285466</span></div>
<div><span mce-data-marked="1">Dim</span><span mce-data-marked="1"> translation1 </span><span mce-data-marked="1">As</span><span mce-data-marked="1"> NXOpen.Point3d = </span><span mce-data-marked="1">New</span><span mce-data-marked="1"> NXOpen.Point3d(-</span><span mce-data-marked="1">3.3086805620987789</span><span mce-data-marked="1">, </span><span mce-data-marked="1">0.62693714873927764</span><span mce-data-marked="1">, -</span><span mce-data-marked="1">3.7567940257052665</span><span mce-data-marked="1">)</span></div>
<div><span mce-data-marked="1">workPart.ModelingViews.WorkView.SetRotationTranslationScale(rotMatrix1, translation1, </span><span mce-data-marked="1">20.087236954786007</span><span mce-data-marked="1">)</span></div>
<br/>
<div><span mce-data-marked="1">Dim</span><span mce-data-marked="1"> rotMatrix2 </span><span mce-data-marked="1">As</span><span mce-data-marked="1"> NXOpen.Matrix3x3 = </span><span mce-data-marked="1">Nothing</span></div>
<div><span mce-data-marked="1">rotMatrix2.Xx = </span><span mce-data-marked="1">0.35230914384389794</span></div>
<div><span mce-data-marked="1">rotMatrix2.Xy = </span><span mce-data-marked="1">0.9320219125607806</span></div>
<div><span mce-data-marked="1">rotMatrix2.Xz = </span><span mce-data-marked="1">0.084931864871331197</span></div>
<div><span mce-data-marked="1">rotMatrix2.Yx = -</span><span mce-data-marked="1">0.80449854395745402</span></div>
<div><span mce-data-marked="1">rotMatrix2.Yy = </span><span mce-data-marked="1">0.25523172209609529</span></div>
<div><span mce-data-marked="1">rotMatrix2.Yz = </span><span mce-data-marked="1">0.53631973747587947</span></div>
<div><span mce-data-marked="1">rotMatrix2.Zx = </span><span mce-data-marked="1">0.47818444133442228</span></div>
<div><span mce-data-marked="1">rotMatrix2.Zy = -</span><span mce-data-marked="1">0.25727790916128879</span></div>
<div><span mce-data-marked="1">rotMatrix2.Zz = </span><span mce-data-marked="1">0.83973074108506962</span></div>
<div><span mce-data-marked="1">Dim</span><span mce-data-marked="1"> translation2 </span><span mce-data-marked="1">As</span><span mce-data-marked="1"> NXOpen.Point3d = </span><span mce-data-marked="1">New</span><span mce-data-marked="1"> NXOpen.Point3d(-</span><span mce-data-marked="1">3.3228413872155782</span><span mce-data-marked="1">, </span><span mce-data-marked="1">0.68621575734774831</span><span mce-data-marked="1">, -</span><span mce-data-marked="1">4.5291485362901351</span><span mce-data-marked="1">)</span></div>
<div><span mce-data-marked="1">workPart.ModelingViews.WorkView.SetRotationTranslationScale(rotMatrix2, translation2, </span><span mce-data-marked="1">20.087236954786007</span><span mce-data-marked="1">)</span></div>
<br/>
<div><span mce-data-marked="1">Dim</span><span mce-data-marked="1"> markId16 </span><span mce-data-marked="1">As</span><span mce-data-marked="1"> NXOpen.Session.UndoMarkId = </span><span mce-data-marked="1">Nothing</span></div>
<div><span mce-data-marked="1">markId16 = theSession.SetUndoMark(NXOpen.Session.MarkVisibility.Invisible, </span><span mce-data-marked="1">"拉伸"</span><span mce-data-marked="1">)</span></div>
<br/>
<div><span mce-data-marked="1">theSession.DeleteUndoMark(markId16, </span><span mce-data-marked="1">Nothing</span><span mce-data-marked="1">)</span></div>
<br/>
<div><span mce-data-marked="1">Dim</span><span mce-data-marked="1"> markId17 </span><span mce-data-marked="1">As</span><span mce-data-marked="1"> NXOpen.Session.UndoMarkId = </span><span mce-data-marked="1">Nothing</span></div>
<div><span mce-data-marked="1">markId17 = theSession.SetUndoMark(NXOpen.Session.MarkVisibility.Invisible, </span><span mce-data-marked="1">"拉伸"</span><span mce-data-marked="1">)</span></div>
<br/>
<div><span mce-data-marked="1">extrudeBuilder1.ParentFeatureInternal = </span><span mce-data-marked="1">False</span></div>
<br/>
<div><span mce-data-marked="1">Dim</span><span mce-data-marked="1"> feature2 </span><span mce-data-marked="1">As</span><span mce-data-marked="1"> NXOpen.Features.Feature = </span><span mce-data-marked="1">Nothing</span></div>
<div><span mce-data-marked="1">feature2 = extrudeBuilder1.CommitFeature()</span></div>
<br/>
<div><span mce-data-marked="1">theSession.DeleteUndoMark(markId17, </span><span mce-data-marked="1">Nothing</span><span mce-data-marked="1">)</span></div>
<br/>
<div><span mce-data-marked="1">theSession.SetUndoMarkName(markId13, </span><span mce-data-marked="1">"拉伸"</span><span mce-data-marked="1">)</span></div>
<br/>
<div><span mce-data-marked="1">Dim</span><span mce-data-marked="1"> expression25 </span><span mce-data-marked="1">As</span><span mce-data-marked="1"> NXOpen.Expression = extrudeBuilder1.Limits.StartExtend.Value</span></div>
<br/>
<div><span mce-data-marked="1">Dim</span><span mce-data-marked="1"> expression26 </span><span mce-data-marked="1">As</span><span mce-data-marked="1"> NXOpen.Expression = extrudeBuilder1.Limits.EndExtend.Value</span></div>
<br/>
<div><span mce-data-marked="1">extrudeBuilder1.Destroy()</span></div>
<br/>
<div><span mce-data-marked="1">workPart.Expressions.Delete(expression23)</span></div>
<br/>
<div><span mce-data-marked="1">workPart.Expressions.Delete(expression24)</span></div>
<br/>
<div><span mce-data-marked="1">Dim</span><span mce-data-marked="1"> rotMatrix3 </span><span mce-data-marked="1">As</span><span mce-data-marked="1"> NXOpen.Matrix3x3 = </span><span mce-data-marked="1">Nothing</span></div>
<div><span mce-data-marked="1">rotMatrix3.Xx = </span><span mce-data-marked="1">0.32369084031626738</span></div>
<div><span mce-data-marked="1">rotMatrix3.Xy = -</span><span mce-data-marked="1">0.25406807483326743</span></div>
<div><span mce-data-marked="1">rotMatrix3.Xz = </span><span mce-data-marked="1">0.91141299817693289</span></div>
<div><span mce-data-marked="1">rotMatrix3.Yx = -</span><span mce-data-marked="1">0.89063788198691607</span></div>
<div><span mce-data-marked="1">rotMatrix3.Yy = </span><span mce-data-marked="1">0.24331311598439376</span></div>
<div><span mce-data-marked="1">rotMatrix3.Yz = </span><span mce-data-marked="1">0.3841391554629961</span></div>
<div><span mce-data-marked="1">rotMatrix3.Zx = -</span><span mce-data-marked="1">0.31935623223166798</span></div>
<div><span mce-data-marked="1">rotMatrix3.Zy = -</span><span mce-data-marked="1">0.93608126834184724</span></div>
<div><span mce-data-marked="1">rotMatrix3.Zz = -</span><span mce-data-marked="1">0.14752442507703645</span></div>
<div><span mce-data-marked="1">Dim</span><span mce-data-marked="1"> translation3 </span><span mce-data-marked="1">As</span><span mce-data-marked="1"> NXOpen.Point3d = </span><span mce-data-marked="1">New</span><span mce-data-marked="1"> NXOpen.Point3d(-</span><span mce-data-marked="1">5.8022847871323835</span><span mce-data-marked="1">, </span><span mce-data-marked="1">1.1427575033863984</span><span mce-data-marked="1">, -</span><span mce-data-marked="1">1.5673830378038165</span><span mce-data-marked="1">)</span></div>
<div><span mce-data-marked="1">workPart.ModelingViews.WorkView.SetRotationTranslationScale(rotMatrix3, translation3, </span><span mce-data-marked="1">20.087236954786007</span><span mce-data-marked="1">)</span></div>
<br/>
<div><span mce-data-marked="1">' ----------------------------------------------</span></div>
<div><span mce-data-marked="1">' 功能表：工具(T)-&gt;動作記錄(J)-&gt;停止錄製(S)</span></div>
<div><span mce-data-marked="1">' ----------------------------------------------</span></div>
<br/>
<div><span mce-data-marked="1">End Sub</span></div>
<div><span mce-data-marked="1">End Module</span></div>
</div>
<br />NX << <a href='NX.html'>Previous</a> <a href='nxopen 組合零件.html'>Next</a> >> nxopen 組合零件</div>

    <!-- footer -->
      <div class="container">
        <div class="row pt-3 mx-auto">
            <p>
            <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
            Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="icon-heart" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank" >Colorlib</a>
            <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
            </p>
        </div>
      </div>
    <!-- for footer -->

        </div> <!-- for site wrap -->
            <!-- <script src="../cmsimde/static/chimper/js/jquery-3.3.1.min.js"></script> -->
            <script src="../cmsimde/static/chimper/js/jquery-migrate-3.0.1.min.js"></script>
            <script src="../cmsimde/static/chimper/js/jquery-ui.js"></script>
            <script src="../cmsimde/static/chimper/js/popper.min.js"></script>
            <script src="../cmsimde/static/chimper/js/bootstrap.min.js"></script>
            <script src="../cmsimde/static/chimper/js/owl.carousel.min.js"></script>
            <script src="../cmsimde/static/chimper/js/jquery.stellar.min.js"></script>
            <script src="../cmsimde/static/chimper/js/jquery.countdown.min.js"></script>
            <script src="../cmsimde/static/chimper/js/jquery.magnific-popup.min.js"></script>
            <script src="../cmsimde/static/chimper/js/bootstrap-datepicker.min.js"></script>
            <script src="../cmsimde/static/chimper/js/aos.js"></script>
            <!--
            <script src="../cmsimde/static/chimper/js/typed.js"></script>
                    <script>
                    var typed = new Typed('.typed-words', {
                    strings: ["Web Apps"," WordPress"," Mobile Apps"],
                    typeSpeed: 80,
                    backSpeed: 80,
                    backDelay: 4000,
                    startDelay: 1000,
                    loop: true,
                    showCursor: true
                    });
                    </script>
            -->
            <script src="../cmsimde/static/chimper/js/main.js"></script>
        
<!-- 啟用 LaTeX equations 編輯 -->
  <!-- <script>
  MathJax = {
    tex: {inlineMath: [['$', '$'], ['\(', '\)']]}
  };
  </script>
  <script id="MathJax-script" async src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js"></script>-->
    </body></html>
        