<h1>About</h1>
<p>網頁: <a href="https://41123207andy.github.io/cd2024/" title="https://41123207andy.github.io/cd2024/">https://41123207andy.github.io/cd2024/</a></p>
<p>網誌: <a href="https://41123207andy.github.io/cd2024//blog" title="https://41123207andy.github.io/cd2024//blog">https://41123207andy.github.io/cd2024//blog</a></p>
<p>簡報: <a href="https://41123207andy.github.io/cd2024/reveal" title="https://41123207andy.github.io/cd2024/reveal">https://41123207andy.github.io/cd2024/reveal</a></p>
<p>倉儲: <a href="https://github.com/41123207Andy/cd2024">https://github.com/41123207Andy/cd2024</a></p>
<p></p>
<h1>cmsimde</h1>
<p><span style="background-color: #ccffcc;">SMap</span> - SiteMap - 依照階次列出網站的所有頁面.</p>
<p><span style="background-color: #ccffcc;">EditA</span> - Edit All page - 將所有頁面放入編輯模式中, 主要用來處理頁面搬遷, 刪除或決定衝突頁面內容版本.</p>
<p><span style="background-color: #ccffcc;">Edit</span> - Edit page - 先選擇要編輯的單一頁面後, 再點選 Edit, 即可進入單一頁面的編輯模式.</p>
<p><span style="background-color: #ccffcc;">Config</span> - Configure Site - 編輯頁面標題與管理者密碼.</p>
<p><span style="background-color: #ccffcc;">Search</span> - 動態頁面內容的關鍵字搜尋.</p>
<p><span style="background-color: #ccffcc;">IUpload</span> - Image file Upload - 圖檔的上傳功能, 可以上傳 jpg, png 與 gif 檔案, 其中若在手機上傳圖檔, 系統會自動將圖片檔案縮小為 800x800 大小.</p>
<p><span style="background-color: #ccffcc;">IList</span> - Image file List - 列出可以直接在頁面編輯模式中引用的圖片檔案.</p>
<p><span style="background-color: #ccffcc;">FUpload</span> - File Upload - 一般檔案的上傳功能, 目前可以上傳的檔案副檔名包括 'jpg', 'png', 'gif', '7z', 'pdf', 'zip', 'ttt', 'stl', 'txt', 'html', 'mp4' 等, 使用者可以自行修改.</p>
<p><span style="background-color: #ccffcc;">FList</span> - File List - 列出可以直接在頁面編輯模式中引用的上傳檔案.</p>
<p><span style="background-color: #ccffcc;">Logout</span> - 登出頁面編輯模式.</p>
<p><span style="background-color: #ccffcc;">Convert</span> - 將動態網站中位於 config/content.htm 檔案, 透過分頁設定轉為 content 目錄中的靜態網頁.</p>
<p><span style="background-color: #ccffcc;">acp</span> - git add, git commit 與 git push, 通常只有在 localhost 或自架主機上利用網頁表單協助將倉儲改版內容推向 Github 倉儲.</p>
<p><span style="background-color: #ccffcc;">SStatic</span> - Start Static Site - 利用 Python 啟動網站伺服功能, 可以讓使用者檢查轉檔後的靜態網站內容.</p>
<p><span style="background-color: #ccffcc;">RStatic</span> - Replit Static Site URL - 僅用於 Replit 模式, 當使用者按下 SStatic 後, 可以按下 RStatic 進入當下尚未推向 Github Pages 的靜態網站.</p>
<p><span style="background-color: #ccffcc;">80</span> - 由 init.py 中 static_port 所決定的連結字串, 一般不使用 80, 只有在 Replit 中為了與動態網站共用 port, 才特別設為 80.</p>
<p></p>
<h1>Replit</h1>
<p><a href="https://replit.com">https://replit.com</a></p>
<p>利用 init_replit 指令安裝所需 Python 模組<br/><br/>chmod u+x init_replit<br/><br/>./init_replit</p>
<p dir="auto">On Replit:</p>
<p dir="auto">.replit: python3 main.py</p>
<p dir="auto">chmod u+x cms init_replit</p>
<p dir="auto">./init_replit</p>
<p dir="auto" style="padding-left: 30px;">for cmsimde_site (not needed): git submodule update --init --recursive</p>
<p dir="auto" style="padding-left: 30px;">for cmsimde: pip install flask flask_cors bs4 lxml pelican markdown gevent</p>
<p dir="auto">password generator: <a href="https://mde.tw/cmsite/content/Brython.html?src=https://gist.githubusercontent.com/mdecycu/b92b16621dd0246c352cf13d6463b333/raw/0bfa669750aba3abe48554509bbd43d65b6e5c82/hashlib_password_generator.py">https://mde.tw/cmsite/content/Brython.html?src=https://gist.githubusercontent.com/mdecycu/b92b16621dd0246c352cf13d6463b333/raw/0bfa669750aba3abe48554509bbd43d65b6e5c82/hashlib_password_generator.py</a> </p>
<p dir="auto"></p>
<p dir="auto">for IPv6 only Ubuntu:<br/><br/>.ssh 目錄中的 config, 將 SSH session 名稱設為 github.com:<br/><br/>Host github.com<br/>User git<br/>Hostname github.com<br/>ProxyCommand /usr/bin/ncat --proxy p4.cycu.org:3128 --proxy-type http %h %p<br/><br/>for Replit:<br/><br/>.ssh 目錄中的 config, 將 SSH session 名稱設為 github.com:<br/><br/>Host github.com<br/>User git<br/>Hostname github.co<br/>#since Replit works for IPv4, therefore no ProxyCommand setting needed<br/>#ProxyCommand /usr/bin/ncat --proxy p4.cycu.org:3128 --proxy-type http %h %p</p>
<p></p>
<p></p>
<h1>Brython</h1>
<p><a href="https://en.wikipedia.org/wiki/Python_(programming_language)">https://en.wikipedia.org/wiki/Python_(programming_language)</a></p>
<h4>Examples:</h4>
<p style="padding-left: 30px;"><a href="https://gist.github.com/mdecycu/d9082d678096bd58378d6afe2c7fa05d">https://gist.github.com/mdecycu/d9082d678096bd58378d6afe2c7fa05d</a></p>
<p style="padding-left: 30px;"><a href="https://www.geeksforgeeks.org/python-programming-examples/">https://www.geeksforgeeks.org/python-programming-examples/</a></p>
<p style="padding-left: 30px;"><a href="https://www.programiz.com/python-programming/examples">https://www.programiz.com/python-programming/examples</a></p>
<p style="padding-left: 30px;"><a href="https://www.freecodecamp.org/news/python-code-examples-sample-script-coding-tutorial-for-beginners/">https://www.freecodecamp.org/news/python-code-examples-sample-script-coding-tutorial-for-beginners/</a></p>
<h4>Python Tutorial:</h4>
<p style="padding-left: 30px;"><a href="https://docs.python.org/3/tutorial/">https://docs.python.org/3/tutorial/</a></p>
<p style="padding-left: 30px;"><a href="https://docs.python.org/3/tutorial/introduction.html">An informal introduction to Python</a></p>
<h4>Indentation (Python 採 4 個 Spaces 縮排, 以界定執行範圍)</h4>
<h4>Variables (<a href="https://github.com/python/cpython/blob/3.11/Lib/keyword.py">Python Keywords</a>)</h4>
<h4>Comments (# 單行註解, 三個單引號或三個雙引號標註多行註解)</h4>
<h4><a href="https://docs.python.org/3/tutorial/introduction.html#numbers">Numbers</a> (整數 int(), 浮點數 float())</h4>
<h4><a href="https://docs.python.org/3/tutorial/introduction.html#strings">Strings</a> (字串)</h4>
<h4>print (Python 內建函式, <a href="https://docs.python.org/3/library/functions.html#print">print()</a> 函式)</h4>
<p><a href="https://docs.python.org/3/tutorial/controlflow.html">Python control flow tools</a></p>
<h4 style="padding-left: 30px;"><a href="https://docs.python.org/3/tutorial/controlflow.html#for-statements">for</a></h4>
<h4 style="padding-left: 30px;"><a href="https://docs.python.org/3/tutorial/controlflow.html#if-statements">if</a></h4>
<h4 style="padding-left: 30px;"><a href="https://docs.python.org/3/tutorial/controlflow.html#the-range-function">range</a></h4>
<h4>open</h4>
<h4>read</h4>
<h4><a href="https://docs.python.org/3/tutorial/introduction.html#lists">lists</a></h4>
<h4><a href="https://docs.python.org/3/tutorial/datastructures.html#tuples-and-sequences">tuples</a></h4>
<h4><a href="https://docs.python.org/3/tutorial/datastructures.html#dictionaries">dictionaries</a></h4>
<h4><a href="https://docs.python.org/3/tutorial/controlflow.html#defining-functions">functions</a></h4>
<h4><a href="https://docs.python.org/3/tutorial/errors.html#exceptions">try ... except</a></h4>
<h4><a href="https://docs.python.org/3/tutorial/controlflow.html#break-and-continue-statements-and-else-clauses-on-loops">break</a></h4>
<h4><a href="https://docs.python.org/3/tutorial/controlflow.html#pass-statements">pass</a></h4>
<h4><a href="https://docs.python.org/3/tutorial/classes.html?highlight=classes">classes</a></h4>
<p>這個頁面 demo 如何在同一頁面下納入多個線上 Ace 編輯器與執行按鈕 (<a href="/downloads/practice_html.txt">practice_html.txt</a> 動態頁面超文件).</p>
<p><a href="/downloads/practice_html.txt">practice_html.txt</a> 動態頁面超文件應該可以在啟動 Brython 時, 設定將 .py 檔案放入 downloads/py 目錄中引用.</p>
<p>亦即將所有對應的 html 也使用 Brython 產生, 然後寫為 <a href="https://docs.python.org/3/tutorial/classes.html">class</a> 後, 在範例導入時透過 <a href="https://docs.python.org/3/tutorial/classes.html#instance-objects">instance</a> 引用.</p>
<pre class="brush:html;auto-links:false;toolbar:false" contenteditable="false">&lt;!-- 啟動 Brython --&gt;
&lt;script&gt;
window.onload=function(){
brython({debug:1, pythonpath:['/static/','./../downloads/py/']});
}
&lt;/script&gt;</pre>
<p>從 1 累加到 100:</p>
<p><button id="add1to100">1 add to 100</button></p>
<p>將 iterable 與 iterator <a href="https://home.gamer.com.tw/creationDetail.php?sn=4337438">相關說明</a>, 利用 Brython 與 Ace Editor 整理在這個頁面.</p>
<p></p>
<h1 class="post-title">NX</h1>
<p><a href="https://nfuedu-my.sharepoint.com/:u:/g/personal/41123207_nfu_edu_tw/EZHqyPV-5shKtkiWgwvou8QB9AnDSVjQyvTLcsPwI_6Awg?e=3gLFbH">NO.4 零件檔案</a></p>
<h2 class="post-title"><span>w12 實習任務一</span></h2>
<p><a href="https://nfuedu-my.sharepoint.com/:u:/g/personal/41123207_nfu_edu_tw/EQJdS7P7A69MsJtAr_IrJI4BvqLRPWEuodDvoKcwlhLlRQ?e=Zzl0PO"><span>NO.4 RECORD.vb</span></a></p>
<div>
<div><span>' NX 1872</span></div>
<div><span>' Journal created by Admin on Thu May 9 15:20:28 2024 台北標準時間</span></div>
<br/>
<div><span>'</span></div>
<div><span>Imports</span><span> System</span></div>
<div><span>Imports</span><span> NXOpen</span></div>
<br/>
<div><span>Module</span><span> NXJournal</span></div>
<div><span>Sub</span><span> Main (</span><span>ByVal</span><span> args() </span><span>As</span><span> </span><span>String</span><span>) </span></div>
<br/>
<div><span>Dim</span><span> theSession </span><span>As</span><span> NXOpen.Session = NXOpen.Session.GetSession()</span></div>
<div><span>Dim</span><span> workPart </span><span>As</span><span> NXOpen.Part = theSession.Parts.Work</span></div>
<br/>
<div><span>Dim</span><span> displayPart </span><span>As</span><span> NXOpen.Part = theSession.Parts.Display</span></div>
<br/>
<div><span>' ----------------------------------------------</span></div>
<div><span>' 功能表：插入(S)-&gt;基準/點(D)-&gt;基準平面(D)...</span></div>
<div><span>' ----------------------------------------------</span></div>
<div><span>Dim</span><span> markId1 </span><span>As</span><span> NXOpen.Session.UndoMarkId = </span><span>Nothing</span></div>
<div><span>markId1 = theSession.SetUndoMark(NXOpen.Session.MarkVisibility.Visible, </span><span>"起點"</span><span>)</span></div>
<br/>
<div><span>Dim</span><span> nullNXOpen_Features_Feature </span><span>As</span><span> NXOpen.Features.Feature = </span><span>Nothing</span></div>
<br/>
<div><span>Dim</span><span> datumPlaneBuilder1 </span><span>As</span><span> NXOpen.Features.DatumPlaneBuilder = </span><span>Nothing</span></div>
<div><span>datumPlaneBuilder1 = workPart.Features.CreateDatumPlaneBuilder(nullNXOpen_Features_Feature)</span></div>
<br/>
<div><span>Dim</span><span> plane1 </span><span>As</span><span> NXOpen.Plane = </span><span>Nothing</span></div>
<div><span>plane1 = datumPlaneBuilder1.GetPlane()</span></div>
<br/>
<div><span>Dim</span><span> unit1 </span><span>As</span><span> NXOpen.Unit = </span><span>CType</span><span>(workPart.UnitCollection.FindObject(</span><span>"MilliMeter"</span><span>), NXOpen.Unit)</span></div>
<br/>
<div><span>Dim</span><span> expression1 </span><span>As</span><span> NXOpen.Expression = </span><span>Nothing</span></div>
<div><span>expression1 = workPart.Expressions.CreateSystemExpressionWithUnits(</span><span>"0"</span><span>, unit1)</span></div>
<br/>
<div><span>Dim</span><span> expression2 </span><span>As</span><span> NXOpen.Expression = </span><span>Nothing</span></div>
<div><span>expression2 = workPart.Expressions.CreateSystemExpressionWithUnits(</span><span>"0"</span><span>, unit1)</span></div>
<br/>
<div><span>Dim</span><span> coordinates1 </span><span>As</span><span> NXOpen.Point3d = </span><span>New</span><span> NXOpen.Point3d(</span><span>0.0</span><span>, </span><span>0.0</span><span>, </span><span>0.0</span><span>)</span></div>
<div><span>Dim</span><span> point1 </span><span>As</span><span> NXOpen.Point = </span><span>Nothing</span></div>
<div><span>point1 = workPart.Points.CreatePoint(coordinates1)</span></div>
<br/>
<div><span>theSession.SetUndoMarkName(markId1, </span><span>"基準平面 對話方塊"</span><span>)</span></div>
<br/>
<div><span>plane1.SetUpdateOption(NXOpen.SmartObject.UpdateOption.WithinModeling)</span></div>
<br/>
<div><span>' ----------------------------------------------</span></div>
<div><span>' 功能表：插入(S)-&gt;基準/點(D)-&gt;基準座標系(C)...</span></div>
<div><span>' ----------------------------------------------</span></div>
<div><span>datumPlaneBuilder1.Destroy()</span></div>
<br/>
<div><span>Try</span></div>
<div><span> </span><span>' 運算式仍然在使用中。</span></div>
<div><span> workPart.Expressions.Delete(expression2)</span></div>
<div><span>Catch</span><span> ex </span><span>As</span><span> NXException</span></div>
<div><span> ex.AssertErrorCode(</span><span>1050029</span><span>)</span></div>
<div><span>End Try</span></div>
<br/>
<div><span>Try</span></div>
<div><span> </span><span>' 運算式仍然在使用中。</span></div>
<div><span> workPart.Expressions.Delete(expression1)</span></div>
<div><span>Catch</span><span> ex </span><span>As</span><span> NXException</span></div>
<div><span> ex.AssertErrorCode(</span><span>1050029</span><span>)</span></div>
<div><span>End Try</span></div>
<br/>
<div><span>theSession.UndoToMark(markId1, </span><span>Nothing</span><span>)</span></div>
<br/>
<div><span>theSession.DeleteUndoMark(markId1, </span><span>Nothing</span><span>)</span></div>
<br/>
<div><span>Dim</span><span> markId2 </span><span>As</span><span> NXOpen.Session.UndoMarkId = </span><span>Nothing</span></div>
<div><span>markId2 = theSession.SetUndoMark(NXOpen.Session.MarkVisibility.Visible, </span><span>"起點"</span><span>)</span></div>
<br/>
<div><span>Dim</span><span> datumCsysBuilder1 </span><span>As</span><span> NXOpen.Features.DatumCsysBuilder = </span><span>Nothing</span></div>
<div><span>datumCsysBuilder1 = workPart.Features.CreateDatumCsysBuilder(nullNXOpen_Features_Feature)</span></div>
<br/>
<div><span>Dim</span><span> origin1 </span><span>As</span><span> NXOpen.Point3d = </span><span>New</span><span> NXOpen.Point3d(</span><span>0.0</span><span>, </span><span>0.0</span><span>, </span><span>0.0</span><span>)</span></div>
<div><span>Dim</span><span> normal1 </span><span>As</span><span> NXOpen.Vector3d = </span><span>New</span><span> NXOpen.Vector3d(</span><span>0.0</span><span>, </span><span>0.0</span><span>, </span><span>1.0</span><span>)</span></div>
<div><span>Dim</span><span> plane2 </span><span>As</span><span> NXOpen.Plane = </span><span>Nothing</span></div>
<div><span>plane2 = workPart.Planes.CreatePlane(origin1, normal1, NXOpen.SmartObject.UpdateOption.WithinModeling)</span></div>
<br/>
<div><span>Dim</span><span> expression3 </span><span>As</span><span> NXOpen.Expression = </span><span>Nothing</span></div>
<div><span>expression3 = workPart.Expressions.CreateSystemExpressionWithUnits(</span><span>"0"</span><span>, unit1)</span></div>
<br/>
<div><span>Dim</span><span> expression4 </span><span>As</span><span> NXOpen.Expression = </span><span>Nothing</span></div>
<div><span>expression4 = workPart.Expressions.CreateSystemExpressionWithUnits(</span><span>"0"</span><span>, unit1)</span></div>
<br/>
<div><span>Dim</span><span> origin2 </span><span>As</span><span> NXOpen.Point3d = </span><span>New</span><span> NXOpen.Point3d(</span><span>0.0</span><span>, </span><span>0.0</span><span>, </span><span>0.0</span><span>)</span></div>
<div><span>Dim</span><span> normal2 </span><span>As</span><span> NXOpen.Vector3d = </span><span>New</span><span> NXOpen.Vector3d(</span><span>0.0</span><span>, </span><span>0.0</span><span>, </span><span>1.0</span><span>)</span></div>
<div><span>Dim</span><span> plane3 </span><span>As</span><span> NXOpen.Plane = </span><span>Nothing</span></div>
<div><span>plane3 = workPart.Planes.CreatePlane(origin2, normal2, NXOpen.SmartObject.UpdateOption.WithinModeling)</span></div>
<br/>
<div><span>Dim</span><span> expression5 </span><span>As</span><span> NXOpen.Expression = </span><span>Nothing</span></div>
<div><span>expression5 = workPart.Expressions.CreateSystemExpressionWithUnits(</span><span>"0"</span><span>, unit1)</span></div>
<br/>
<div><span>Dim</span><span> expression6 </span><span>As</span><span> NXOpen.Expression = </span><span>Nothing</span></div>
<div><span>expression6 = workPart.Expressions.CreateSystemExpressionWithUnits(</span><span>"0"</span><span>, unit1)</span></div>
<br/>
<div><span>Dim</span><span> origin3 </span><span>As</span><span> NXOpen.Point3d = </span><span>New</span><span> NXOpen.Point3d(</span><span>0.0</span><span>, </span><span>0.0</span><span>, </span><span>0.0</span><span>)</span></div>
<div><span>Dim</span><span> normal3 </span><span>As</span><span> NXOpen.Vector3d = </span><span>New</span><span> NXOpen.Vector3d(</span><span>0.0</span><span>, </span><span>0.0</span><span>, </span><span>1.0</span><span>)</span></div>
<div><span>Dim</span><span> plane4 </span><span>As</span><span> NXOpen.Plane = </span><span>Nothing</span></div>
<div><span>plane4 = workPart.Planes.CreatePlane(origin3, normal3, NXOpen.SmartObject.UpdateOption.WithinModeling)</span></div>
<br/>
<div><span>Dim</span><span> expression7 </span><span>As</span><span> NXOpen.Expression = </span><span>Nothing</span></div>
<div><span>expression7 = workPart.Expressions.CreateSystemExpressionWithUnits(</span><span>"0"</span><span>, unit1)</span></div>
<br/>
<div><span>Dim</span><span> expression8 </span><span>As</span><span> NXOpen.Expression = </span><span>Nothing</span></div>
<div><span>expression8 = workPart.Expressions.CreateSystemExpressionWithUnits(</span><span>"0"</span><span>, unit1)</span></div>
<br/>
<div><span>Dim</span><span> origin4 </span><span>As</span><span> NXOpen.Point3d = </span><span>New</span><span> NXOpen.Point3d(</span><span>0.0</span><span>, </span><span>0.0</span><span>, </span><span>0.0</span><span>)</span></div>
<div><span>Dim</span><span> normal4 </span><span>As</span><span> NXOpen.Vector3d = </span><span>New</span><span> NXOpen.Vector3d(</span><span>0.0</span><span>, </span><span>0.0</span><span>, </span><span>1.0</span><span>)</span></div>
<div><span>Dim</span><span> plane5 </span><span>As</span><span> NXOpen.Plane = </span><span>Nothing</span></div>
<div><span>plane5 = workPart.Planes.CreatePlane(origin4, normal4, NXOpen.SmartObject.UpdateOption.WithinModeling)</span></div>
<br/>
<div><span>Dim</span><span> expression9 </span><span>As</span><span> NXOpen.Expression = </span><span>Nothing</span></div>
<div><span>expression9 = workPart.Expressions.CreateSystemExpressionWithUnits(</span><span>"0"</span><span>, unit1)</span></div>
<br/>
<div><span>Dim</span><span> expression10 </span><span>As</span><span> NXOpen.Expression = </span><span>Nothing</span></div>
<div><span>expression10 = workPart.Expressions.CreateSystemExpressionWithUnits(</span><span>"0"</span><span>, unit1)</span></div>
<br/>
<div><span>Dim</span><span> unit2 </span><span>As</span><span> NXOpen.Unit = </span><span>CType</span><span>(workPart.UnitCollection.FindObject(</span><span>"Degrees"</span><span>), NXOpen.Unit)</span></div>
<br/>
<div><span>Dim</span><span> expression11 </span><span>As</span><span> NXOpen.Expression = </span><span>Nothing</span></div>
<div><span>expression11 = workPart.Expressions.CreateSystemExpressionWithUnits(</span><span>"0"</span><span>, unit2)</span></div>
<br/>
<div><span>Dim</span><span> expression12 </span><span>As</span><span> NXOpen.Expression = </span><span>Nothing</span></div>
<div><span>expression12 = workPart.Expressions.CreateSystemExpressionWithUnits(</span><span>"0"</span><span>, unit2)</span></div>
<br/>
<div><span>Dim</span><span> expression13 </span><span>As</span><span> NXOpen.Expression = </span><span>Nothing</span></div>
<div><span>expression13 = workPart.Expressions.CreateSystemExpressionWithUnits(</span><span>"0"</span><span>, unit2)</span></div>
<br/>
<div><span>Dim</span><span> expression14 </span><span>As</span><span> NXOpen.Expression = </span><span>Nothing</span></div>
<div><span>expression14 = workPart.Expressions.CreateSystemExpressionWithUnits(</span><span>"0"</span><span>, unit1)</span></div>
<br/>
<div><span>Dim</span><span> expression15 </span><span>As</span><span> NXOpen.Expression = </span><span>Nothing</span></div>
<div><span>expression15 = workPart.Expressions.CreateSystemExpressionWithUnits(</span><span>"0"</span><span>, unit2)</span></div>
<br/>
<div><span>Dim</span><span> expression16 </span><span>As</span><span> NXOpen.Expression = </span><span>Nothing</span></div>
<div><span>expression16 = workPart.Expressions.CreateSystemExpressionWithUnits(</span><span>"0"</span><span>, unit1)</span></div>
<br/>
<div><span>Dim</span><span> expression17 </span><span>As</span><span> NXOpen.Expression = </span><span>Nothing</span></div>
<div><span>expression17 = workPart.Expressions.CreateSystemExpressionWithUnits(</span><span>"0"</span><span>, unit2)</span></div>
<br/>
<div><span>Dim</span><span> expression18 </span><span>As</span><span> NXOpen.Expression = </span><span>Nothing</span></div>
<div><span>expression18 = workPart.Expressions.CreateSystemExpressionWithUnits(</span><span>"0"</span><span>, unit1)</span></div>
<br/>
<div><span>Dim</span><span> expression19 </span><span>As</span><span> NXOpen.Expression = </span><span>Nothing</span></div>
<div><span>expression19 = workPart.Expressions.CreateSystemExpressionWithUnits(</span><span>"0"</span><span>, unit2)</span></div>
<br/>
<div><span>expression14.RightHandSide = </span><span>"0"</span></div>
<br/>
<div><span>expression16.RightHandSide = </span><span>"0"</span></div>
<br/>
<div><span>expression18.RightHandSide = </span><span>"0"</span></div>
<br/>
<div><span>expression15.RightHandSide = </span><span>"0"</span></div>
<br/>
<div><span>expression17.RightHandSide = </span><span>"0"</span></div>
<br/>
<div><span>expression19.RightHandSide = </span><span>"0"</span></div>
<br/>
<div><span>theSession.SetUndoMarkName(markId2, </span><span>"基準座標系 對話方塊"</span><span>)</span></div>
<br/>
<div><span>' ----------------------------------------------</span></div>
<div><span>' 功能表：插入(S)-&gt;草圖(H)...</span></div>
<div><span>' ----------------------------------------------</span></div>
<div><span>Dim</span><span> markId3 </span><span>As</span><span> NXOpen.Session.UndoMarkId = </span><span>Nothing</span></div>
<div><span>markId3 = theSession.SetUndoMark(NXOpen.Session.MarkVisibility.Invisible, </span><span>"基準座標系"</span><span>)</span></div>
<br/>
<div><span>theSession.DeleteUndoMark(markId3, </span><span>Nothing</span><span>)</span></div>
<br/>
<div><span>Dim</span><span> markId4 </span><span>As</span><span> NXOpen.Session.UndoMarkId = </span><span>Nothing</span></div>
<div><span>markId4 = theSession.SetUndoMark(NXOpen.Session.MarkVisibility.Invisible, </span><span>"基準座標系"</span><span>)</span></div>
<br/>
<div><span>Dim</span><span> origin5 </span><span>As</span><span> NXOpen.Point3d = </span><span>New</span><span> NXOpen.Point3d(</span><span>0.0</span><span>, </span><span>0.0</span><span>, </span><span>0.0</span><span>)</span></div>
<div><span>Dim</span><span> xDirection1 </span><span>As</span><span> NXOpen.Vector3d = </span><span>New</span><span> NXOpen.Vector3d(</span><span>1.0</span><span>, </span><span>0.0</span><span>, </span><span>0.0</span><span>)</span></div>
<div><span>Dim</span><span> yDirection1 </span><span>As</span><span> NXOpen.Vector3d = </span><span>New</span><span> NXOpen.Vector3d(</span><span>0.0</span><span>, </span><span>1.0</span><span>, </span><span>0.0</span><span>)</span></div>
<div><span>Dim</span><span> xform1 </span><span>As</span><span> NXOpen.Xform = </span><span>Nothing</span></div>
<div><span>xform1 = workPart.Xforms.CreateXform(origin5, xDirection1, yDirection1, NXOpen.SmartObject.UpdateOption.WithinModeling, </span><span>1.0</span><span>)</span></div>
<br/>
<div><span>Dim</span><span> cartesianCoordinateSystem1 </span><span>As</span><span> NXOpen.CartesianCoordinateSystem = </span><span>Nothing</span></div>
<div><span>cartesianCoordinateSystem1 = workPart.CoordinateSystems.CreateCoordinateSystem(xform1, NXOpen.SmartObject.UpdateOption.WithinModeling)</span></div>
<br/>
<div><span>theSession.DeleteUndoMark(markId4, </span><span>Nothing</span><span>)</span></div>
<br/>
<div><span>theSession.SetUndoMarkName(markId2, </span><span>"基準座標系"</span><span>)</span></div>
<br/>
<div><span>workPart.Expressions.Delete(expression14)</span></div>
<br/>
<div><span>workPart.Expressions.Delete(expression16)</span></div>
<br/>
<div><span>workPart.Expressions.Delete(expression18)</span></div>
<br/>
<div><span>workPart.Expressions.Delete(expression15)</span></div>
<br/>
<div><span>workPart.Expressions.Delete(expression17)</span></div>
<br/>
<div><span>workPart.Expressions.Delete(expression19)</span></div>
<br/>
<div><span>workPart.Expressions.Delete(expression11)</span></div>
<br/>
<div><span>workPart.Expressions.Delete(expression12)</span></div>
<br/>
<div><span>workPart.Expressions.Delete(expression13)</span></div>
<br/>
<div><span>Try</span></div>
<div><span> </span><span>' 運算式仍然在使用中。</span></div>
<div><span> workPart.Expressions.Delete(expression4)</span></div>
<div><span>Catch</span><span> ex </span><span>As</span><span> NXException</span></div>
<div><span> ex.AssertErrorCode(</span><span>1050029</span><span>)</span></div>
<div><span>End Try</span></div>
<br/>
<div><span>Try</span></div>
<div><span> </span><span>' 運算式仍然在使用中。</span></div>
<div><span> workPart.Expressions.Delete(expression6)</span></div>
<div><span>Catch</span><span> ex </span><span>As</span><span> NXException</span></div>
<div><span> ex.AssertErrorCode(</span><span>1050029</span><span>)</span></div>
<div><span>End Try</span></div>
<br/>
<div><span>Try</span></div>
<div><span> </span><span>' 運算式仍然在使用中。</span></div>
<div><span> workPart.Expressions.Delete(expression8)</span></div>
<div><span>Catch</span><span> ex </span><span>As</span><span> NXException</span></div>
<div><span> ex.AssertErrorCode(</span><span>1050029</span><span>)</span></div>
<div><span>End Try</span></div>
<br/>
<div><span>Try</span></div>
<div><span> </span><span>' 運算式仍然在使用中。</span></div>
<div><span> workPart.Expressions.Delete(expression10)</span></div>
<div><span>Catch</span><span> ex </span><span>As</span><span> NXException</span></div>
<div><span> ex.AssertErrorCode(</span><span>1050029</span><span>)</span></div>
<div><span>End Try</span></div>
<br/>
<div><span>Try</span></div>
<div><span> </span><span>' 運算式仍然在使用中。</span></div>
<div><span> workPart.Expressions.Delete(expression3)</span></div>
<div><span>Catch</span><span> ex </span><span>As</span><span> NXException</span></div>
<div><span> ex.AssertErrorCode(</span><span>1050029</span><span>)</span></div>
<div><span>End Try</span></div>
<br/>
<div><span>plane2.DestroyPlane()</span></div>
<br/>
<div><span>Try</span></div>
<div><span> </span><span>' 運算式仍然在使用中。</span></div>
<div><span> workPart.Expressions.Delete(expression5)</span></div>
<div><span>Catch</span><span> ex </span><span>As</span><span> NXException</span></div>
<div><span> ex.AssertErrorCode(</span><span>1050029</span><span>)</span></div>
<div><span>End Try</span></div>
<br/>
<div><span>plane3.DestroyPlane()</span></div>
<br/>
<div><span>Try</span></div>
<div><span> </span><span>' 運算式仍然在使用中。</span></div>
<div><span> workPart.Expressions.Delete(expression7)</span></div>
<div><span>Catch</span><span> ex </span><span>As</span><span> NXException</span></div>
<div><span> ex.AssertErrorCode(</span><span>1050029</span><span>)</span></div>
<div><span>End Try</span></div>
<br/>
<div><span>plane4.DestroyPlane()</span></div>
<br/>
<div><span>Try</span></div>
<div><span> </span><span>' 運算式仍然在使用中。</span></div>
<div><span> workPart.Expressions.Delete(expression9)</span></div>
<div><span>Catch</span><span> ex </span><span>As</span><span> NXException</span></div>
<div><span> ex.AssertErrorCode(</span><span>1050029</span><span>)</span></div>
<div><span>End Try</span></div>
<br/>
<div><span>plane5.DestroyPlane()</span></div>
<br/>
<div><span>datumCsysBuilder1.Csys = cartesianCoordinateSystem1</span></div>
<br/>
<div><span>datumCsysBuilder1.DisplayScaleFactor = </span><span>1.25</span></div>
<br/>
<div><span>Dim</span><span> nXObject1 </span><span>As</span><span> NXOpen.NXObject = </span><span>Nothing</span></div>
<div><span>nXObject1 = datumCsysBuilder1.Commit()</span></div>
<br/>
<div><span>datumCsysBuilder1.Destroy()</span></div>
<br/>
<div><span>Dim</span><span> markId5 </span><span>As</span><span> NXOpen.Session.UndoMarkId = </span><span>Nothing</span></div>
<div><span>markId5 = theSession.SetUndoMark(NXOpen.Session.MarkVisibility.Visible, </span><span>"起點"</span><span>)</span></div>
<br/>
<div><span>Dim</span><span> nullNXOpen_Sketch </span><span>As</span><span> NXOpen.Sketch = </span><span>Nothing</span></div>
<br/>
<div><span>Dim</span><span> sketchInPlaceBuilder1 </span><span>As</span><span> NXOpen.SketchInPlaceBuilder = </span><span>Nothing</span></div>
<div><span>sketchInPlaceBuilder1 = workPart.Sketches.CreateSketchInPlaceBuilder2(nullNXOpen_Sketch)</span></div>
<br/>
<div><span>Dim</span><span> origin6 </span><span>As</span><span> NXOpen.Point3d = </span><span>New</span><span> NXOpen.Point3d(</span><span>0.0</span><span>, </span><span>0.0</span><span>, </span><span>0.0</span><span>)</span></div>
<div><span>Dim</span><span> normal5 </span><span>As</span><span> NXOpen.Vector3d = </span><span>New</span><span> NXOpen.Vector3d(</span><span>0.0</span><span>, </span><span>0.0</span><span>, </span><span>1.0</span><span>)</span></div>
<div><span>Dim</span><span> plane6 </span><span>As</span><span> NXOpen.Plane = </span><span>Nothing</span></div>
<div><span>plane6 = workPart.Planes.CreatePlane(origin6, normal5, NXOpen.SmartObject.UpdateOption.WithinModeling)</span></div>
<br/>
<div><span>sketchInPlaceBuilder1.PlaneReference = plane6</span></div>
<br/>
<div><span>Dim</span><span> expression20 </span><span>As</span><span> NXOpen.Expression = </span><span>Nothing</span></div>
<div><span>expression20 = workPart.Expressions.CreateSystemExpressionWithUnits(</span><span>"0"</span><span>, unit1)</span></div>
<br/>
<div><span>Dim</span><span> expression21 </span><span>As</span><span> NXOpen.Expression = </span><span>Nothing</span></div>
<div><span>expression21 = workPart.Expressions.CreateSystemExpressionWithUnits(</span><span>"0"</span><span>, unit1)</span></div>
<br/>
<div><span>Dim</span><span> sketchAlongPathBuilder1 </span><span>As</span><span> NXOpen.SketchAlongPathBuilder = </span><span>Nothing</span></div>
<div><span>sketchAlongPathBuilder1 = workPart.Sketches.CreateSketchAlongPathBuilder(nullNXOpen_Sketch)</span></div>
<br/>
<div><span>theSession.SetUndoMarkName(markId5, </span><span>"建立草圖 對話方塊"</span><span>)</span></div>
<br/>
<div><span>Dim</span><span> markId6 </span><span>As</span><span> NXOpen.Session.UndoMarkId = </span><span>Nothing</span></div>
<div><span>markId6 = theSession.SetUndoMark(NXOpen.Session.MarkVisibility.Invisible, </span><span>"建立草圖"</span><span>)</span></div>
<br/>
<div><span>theSession.DeleteUndoMark(markId6, </span><span>Nothing</span><span>)</span></div>
<br/>
<div><span>Dim</span><span> markId7 </span><span>As</span><span> NXOpen.Session.UndoMarkId = </span><span>Nothing</span></div>
<div><span>markId7 = theSession.SetUndoMark(NXOpen.Session.MarkVisibility.Invisible, </span><span>"建立草圖"</span><span>)</span></div>
<br/>
<div><span>theSession.Preferences.Sketch.CreateInferredConstraints = </span><span>True</span></div>
<br/>
<div><span>theSession.Preferences.Sketch.ContinuousAutoDimensioning = </span><span>True</span></div>
<br/>
<div><span>theSession.Preferences.Sketch.DimensionLabel = NXOpen.Preferences.SketchPreferences.DimensionLabelType.Expression</span></div>
<br/>
<div><span>theSession.Preferences.Sketch.TextSizeFixed = </span><span>True</span></div>
<br/>
<div><span>theSession.Preferences.Sketch.FixedTextSize = </span><span>3.0</span></div>
<br/>
<div><span>theSession.Preferences.Sketch.DisplayParenthesesOnReferenceDimensions = </span><span>True</span></div>
<br/>
<div><span>theSession.Preferences.Sketch.DisplayReferenceGeometry = </span><span>False</span></div>
<br/>
<div><span>theSession.Preferences.Sketch.ConstraintSymbolSize = </span><span>3.0</span></div>
<br/>
<div><span>theSession.Preferences.Sketch.DisplayObjectColor = </span><span>False</span></div>
<br/>
<div><span>theSession.Preferences.Sketch.DisplayObjectName = </span><span>True</span></div>
<br/>
<div><span>Dim</span><span> nXObject2 </span><span>As</span><span> NXOpen.NXObject = </span><span>Nothing</span></div>
<div><span>nXObject2 = sketchInPlaceBuilder1.Commit()</span></div>
<br/>
<div><span>Dim</span><span> sketch1 </span><span>As</span><span> NXOpen.Sketch = </span><span>CType</span><span>(nXObject2, NXOpen.Sketch)</span></div>
<br/>
<div><span>Dim</span><span> feature1 </span><span>As</span><span> NXOpen.Features.Feature = </span><span>Nothing</span></div>
<div><span>feature1 = sketch1.Feature</span></div>
<br/>
<div><span>Dim</span><span> markId8 </span><span>As</span><span> NXOpen.Session.UndoMarkId = </span><span>Nothing</span></div>
<div><span>markId8 = theSession.SetUndoMark(NXOpen.Session.MarkVisibility.Invisible, </span><span>"update"</span><span>)</span></div>
<br/>
<div><span>Dim</span><span> nErrs1 </span><span>As</span><span> </span><span>Integer</span><span> = </span><span>Nothing</span></div>
<div><span>nErrs1 = theSession.UpdateManager.DoUpdate(markId8)</span></div>
<br/>
<div><span>sketch1.Activate(NXOpen.Sketch.ViewReorient.</span><span>True</span><span>)</span></div>
<br/>
<div><span>theSession.DeleteUndoMark(markId7, </span><span>Nothing</span><span>)</span></div>
<br/>
<div><span>theSession.SetUndoMarkName(markId5, </span><span>"建立草圖"</span><span>)</span></div>
<br/>
<div><span>sketchInPlaceBuilder1.Destroy()</span></div>
<br/>
<div><span>sketchAlongPathBuilder1.Destroy()</span></div>
<br/>
<div><span>Try</span></div>
<div><span> </span><span>' 運算式仍然在使用中。</span></div>
<div><span> workPart.Expressions.Delete(expression21)</span></div>
<div><span>Catch</span><span> ex </span><span>As</span><span> NXException</span></div>
<div><span> ex.AssertErrorCode(</span><span>1050029</span><span>)</span></div>
<div><span>End Try</span></div>
<br/>
<div><span>Try</span></div>
<div><span> </span><span>' 運算式仍然在使用中。</span></div>
<div><span> workPart.Expressions.Delete(expression20)</span></div>
<div><span>Catch</span><span> ex </span><span>As</span><span> NXException</span></div>
<div><span> ex.AssertErrorCode(</span><span>1050029</span><span>)</span></div>
<div><span>End Try</span></div>
<br/>
<div><span>plane6.DestroyPlane()</span></div>
<br/>
<div><span>Dim</span><span> scaleAboutPoint1 </span><span>As</span><span> NXOpen.Point3d = </span><span>New</span><span> NXOpen.Point3d(</span><span>0.32929284143071819</span><span>, -</span><span>0.40832312337407828</span><span>, </span><span>0.0</span><span>)</span></div>
<div><span>Dim</span><span> viewCenter1 </span><span>As</span><span> NXOpen.Point3d = </span><span>New</span><span> NXOpen.Point3d(-</span><span>0.3292928414306901</span><span>, </span><span>0.4083231233740659</span><span>, </span><span>0.0</span><span>)</span></div>
<div><span>workPart.ModelingViews.WorkView.ZoomAboutPoint(</span><span>1.25</span><span>, scaleAboutPoint1, viewCenter1)</span></div>
<br/>
<div><span>Dim</span><span> scaleAboutPoint2 </span><span>As</span><span> NXOpen.Point3d = </span><span>New</span><span> NXOpen.Point3d(</span><span>0.1159110801836211</span><span>, -</span><span>0.29504638592191679</span><span>, </span><span>0.0</span><span>)</span></div>
<div><span>Dim</span><span> viewCenter2 </span><span>As</span><span> NXOpen.Point3d = </span><span>New</span><span> NXOpen.Point3d(-</span><span>0.11591108018359235</span><span>, </span><span>0.29504638592190419</span><span>, </span><span>0.0</span><span>)</span></div>
<div><span>workPart.ModelingViews.WorkView.ZoomAboutPoint(</span><span>1.25</span><span>, scaleAboutPoint2, viewCenter2)</span></div>
<br/>
<div><span>Dim</span><span> scaleAboutPoint3 </span><span>As</span><span> NXOpen.Point3d = </span><span>New</span><span> NXOpen.Point3d(</span><span>0.059009277184396122</span><span>, -</span><span>0.23603710873753417</span><span>, </span><span>0.0</span><span>)</span></div>
<div><span>Dim</span><span> viewCenter3 </span><span>As</span><span> NXOpen.Point3d = </span><span>New</span><span> NXOpen.Point3d(-</span><span>0.059009277184367367</span><span>, </span><span>0.23603710873752196</span><span>, </span><span>0.0</span><span>)</span></div>
<div><span>workPart.ModelingViews.WorkView.ZoomAboutPoint(</span><span>1.25</span><span>, scaleAboutPoint3, viewCenter3)</span></div>
<br/>
<div><span>Dim</span><span> scaleAboutPoint4 </span><span>As</span><span> NXOpen.Point3d = </span><span>New</span><span> NXOpen.Point3d(</span><span>0.047207421747519185</span><span>, -</span><span>0.18882968699002903</span><span>, </span><span>0.0</span><span>)</span></div>
<div><span>Dim</span><span> viewCenter4 </span><span>As</span><span> NXOpen.Point3d = </span><span>New</span><span> NXOpen.Point3d(-</span><span>0.047207421747490437</span><span>, </span><span>0.18882968699001637</span><span>, </span><span>0.0</span><span>)</span></div>
<div><span>workPart.ModelingViews.WorkView.ZoomAboutPoint(</span><span>0.80000000000000004</span><span>, scaleAboutPoint4, viewCenter4)</span></div>
<br/>
<div><span>Dim</span><span> scaleAboutPoint5 </span><span>As</span><span> NXOpen.Point3d = </span><span>New</span><span> NXOpen.Point3d(</span><span>0.059009277184396101</span><span>, -</span><span>0.23603710873753411</span><span>, </span><span>0.0</span><span>)</span></div>
<div><span>Dim</span><span> viewCenter5 </span><span>As</span><span> NXOpen.Point3d = </span><span>New</span><span> NXOpen.Point3d(-</span><span>0.059009277184367354</span><span>, </span><span>0.23603710873752259</span><span>, </span><span>0.0</span><span>)</span></div>
<div><span>workPart.ModelingViews.WorkView.ZoomAboutPoint(</span><span>0.80000000000000004</span><span>, scaleAboutPoint5, viewCenter5)</span></div>
<br/>
<div><span>Dim</span><span> scaleAboutPoint6 </span><span>As</span><span> NXOpen.Point3d = </span><span>New</span><span> NXOpen.Point3d(</span><span>0.073761596480491534</span><span>, -</span><span>0.29504638592191579</span><span>, </span><span>0.0</span><span>)</span></div>
<div><span>Dim</span><span> viewCenter6 </span><span>As</span><span> NXOpen.Point3d = </span><span>New</span><span> NXOpen.Point3d(-</span><span>0.073761596480462779</span><span>, </span><span>0.29504638592190413</span><span>, </span><span>0.0</span><span>)</span></div>
<div><span>workPart.ModelingViews.WorkView.ZoomAboutPoint(</span><span>0.80000000000000004</span><span>, scaleAboutPoint6, viewCenter6)</span></div>
<br/>
<div><span>Dim</span><span> scaleAboutPoint7 </span><span>As</span><span> NXOpen.Point3d = </span><span>New</span><span> NXOpen.Point3d(</span><span>0.092201995600609918</span><span>, -</span><span>0.3688079824023936</span><span>, </span><span>0.0</span><span>)</span></div>
<div><span>Dim</span><span> viewCenter7 </span><span>As</span><span> NXOpen.Point3d = </span><span>New</span><span> NXOpen.Point3d(-</span><span>0.092201995600580719</span><span>, </span><span>0.36880798240238238</span><span>, </span><span>0.0</span><span>)</span></div>
<div><span>workPart.ModelingViews.WorkView.ZoomAboutPoint(</span><span>0.80000000000000004</span><span>, scaleAboutPoint7, viewCenter7)</span></div>
<br/>
<div><span>Dim</span><span> scaleAboutPoint8 </span><span>As</span><span> NXOpen.Point3d = </span><span>New</span><span> NXOpen.Point3d(</span><span>0.18111106278689948</span><span>, -</span><span>0.32929284143070936</span><span>, </span><span>0.0</span><span>)</span></div>
<div><span>Dim</span><span> viewCenter8 </span><span>As</span><span> NXOpen.Point3d = </span><span>New</span><span> NXOpen.Point3d(-</span><span>0.18111106278687139</span><span>, </span><span>0.32929284143069809</span><span>, </span><span>0.0</span><span>)</span></div>
<div><span>workPart.ModelingViews.WorkView.ZoomAboutPoint(</span><span>1.25</span><span>, scaleAboutPoint8, viewCenter8)</span></div>
<br/>
<div><span>' ----------------------------------------------</span></div>
<div><span>' 功能表：插入(S)-&gt;草圖曲線(S)-&gt;圓(C)...</span></div>
<div><span>' ----------------------------------------------</span></div>
<div><span>Dim</span><span> markId9 </span><span>As</span><span> NXOpen.Session.UndoMarkId = </span><span>Nothing</span></div>
<div><span>markId9 = theSession.SetUndoMark(NXOpen.Session.MarkVisibility.Invisible, </span><span>"Profile short list"</span><span>)</span></div>
<br/>
<div><span>Dim</span><span> markId10 </span><span>As</span><span> NXOpen.Session.UndoMarkId = </span><span>Nothing</span></div>
<div><span>markId10 = theSession.SetUndoMark(NXOpen.Session.MarkVisibility.Invisible, </span><span>"Curve"</span><span>)</span></div>
<br/>
<div><span>Dim</span><span> expression22 </span><span>As</span><span> NXOpen.Expression = </span><span>Nothing</span></div>
<div><span>expression22 = workPart.Expressions.CreateSystemExpression(</span><span>"2.8"</span><span>)</span></div>
<br/>
<div><span>theSession.SetUndoMarkVisibility(markId10, </span><span>"Curve"</span><span>, NXOpen.Session.MarkVisibility.Visible)</span></div>
<br/>
<div><span>Dim</span><span> nXMatrix1 </span><span>As</span><span> NXOpen.NXMatrix = </span><span>Nothing</span></div>
<div><span>nXMatrix1 = theSession.ActiveSketch.Orientation</span></div>
<br/>
<div><span>Dim</span><span> center1 </span><span>As</span><span> NXOpen.Point3d = </span><span>New</span><span> NXOpen.Point3d(</span><span>0.0</span><span>, </span><span>0.0</span><span>, </span><span>0.0</span><span>)</span></div>
<div><span>Dim</span><span> arc1 </span><span>As</span><span> NXOpen.Arc = </span><span>Nothing</span></div>
<div><span>arc1 = workPart.Curves.CreateArc(center1, nXMatrix1, </span><span>1.3999999999999999</span><span>, </span><span>0.0</span><span>, ( </span><span>360.0</span><span> * Math.Pi/</span><span>180.0</span><span> ))</span></div>
<br/>
<div><span>theSession.ActiveSketch.AddGeometry(arc1, NXOpen.Sketch.InferConstraintsOption.InferNoConstraints)</span></div>
<br/>
<div><span>Dim</span><span> geom1_1 </span><span>As</span><span> NXOpen.Sketch.ConstraintGeometry = </span><span>Nothing</span></div>
<div><span>geom1_1.Geometry = arc1</span></div>
<div><span>geom1_1.PointType = NXOpen.Sketch.ConstraintPointType.ArcCenter</span></div>
<div><span>geom1_1.SplineDefiningPointIndex = </span><span>0</span></div>
<div><span>Dim</span><span> geom2_1 </span><span>As</span><span> NXOpen.Sketch.ConstraintGeometry = </span><span>Nothing</span></div>
<div><span>Dim</span><span> datumCsys1 </span><span>As</span><span> NXOpen.Features.DatumCsys = </span><span>CType</span><span>(workPart.Features.FindObject(</span><span>"SKETCH(1:1B)"</span><span>), NXOpen.Features.DatumCsys)</span></div>
<br/>
<div><span>Dim</span><span> point2 </span><span>As</span><span> NXOpen.Point = </span><span>CType</span><span>(datumCsys1.FindObject(</span><span>"POINT 1"</span><span>), NXOpen.Point)</span></div>
<br/>
<div><span>geom2_1.Geometry = point2</span></div>
<div><span>geom2_1.PointType = NXOpen.Sketch.ConstraintPointType.None</span></div>
<div><span>geom2_1.SplineDefiningPointIndex = </span><span>0</span></div>
<div><span>Dim</span><span> sketchGeometricConstraint1 </span><span>As</span><span> NXOpen.SketchGeometricConstraint = </span><span>Nothing</span></div>
<div><span>sketchGeometricConstraint1 = theSession.ActiveSketch.CreateCoincidentConstraint(geom1_1, geom2_1)</span></div>
<br/>
<div><span>Dim</span><span> dimObject1_1 </span><span>As</span><span> NXOpen.Sketch.DimensionGeometry = </span><span>Nothing</span></div>
<div><span>dimObject1_1.Geometry = arc1</span></div>
<div><span>dimObject1_1.AssocType = NXOpen.Sketch.AssocType.None</span></div>
<div><span>dimObject1_1.AssocValue = </span><span>0</span></div>
<div><span>dimObject1_1.HelpPoint.X = </span><span>0.0</span></div>
<div><span>dimObject1_1.HelpPoint.Y = </span><span>0.0</span></div>
<div><span>dimObject1_1.HelpPoint.Z = </span><span>0.0</span></div>
<div><span>Dim</span><span> nullNXOpen_NXObject </span><span>As</span><span> NXOpen.NXObject = </span><span>Nothing</span></div>
<br/>
<div><span>dimObject1_1.View = nullNXOpen_NXObject</span></div>
<div><span>Dim</span><span> dimOrigin1 </span><span>As</span><span> NXOpen.Point3d = </span><span>New</span><span> NXOpen.Point3d(</span><span>0.0</span><span>, </span><span>0.14934856430242965</span><span>, </span><span>0.0</span><span>)</span></div>
<div><span>Dim</span><span> sketchDimensionalConstraint1 </span><span>As</span><span> NXOpen.SketchDimensionalConstraint = </span><span>Nothing</span></div>
<div><span>sketchDimensionalConstraint1 = theSession.ActiveSketch.CreateDiameterDimension(dimObject1_1, dimOrigin1, expression22, NXOpen.Sketch.DimensionOption.CreateAsDriving)</span></div>
<br/>
<div><span>Dim</span><span> dimension1 </span><span>As</span><span> NXOpen.Annotations.Dimension = </span><span>Nothing</span></div>
<div><span>dimension1 = sketchDimensionalConstraint1.AssociatedDimension</span></div>
<br/>
<div><span>theSession.ActiveSketch.Update()</span></div>
<br/>
<div><span>Dim</span><span> markId11 </span><span>As</span><span> NXOpen.Session.UndoMarkId = </span><span>Nothing</span></div>
<div><span>markId11 = theSession.SetUndoMark(NXOpen.Session.MarkVisibility.Invisible, </span><span>"Curve"</span><span>)</span></div>
<br/>
<div><span>' ----------------------------------------------</span></div>
<div><span>' 功能表：渲染樣式(D)-&gt;藝術外觀(T)</span></div>
<div><span>' ----------------------------------------------</span></div>
<div><span>Dim</span><span> nullNXOpen_Display_TrueStudio </span><span>As</span><span> NXOpen.Display.TrueStudio = </span><span>Nothing</span></div>
<br/>
<div><span>Dim</span><span> trueStudioBuilder1 </span><span>As</span><span> NXOpen.Display.TrueStudioBuilder = </span><span>Nothing</span></div>
<div><span>trueStudioBuilder1 = workPart.TrueStudioObjs.CreateTrueStudioBuilder(nullNXOpen_Display_TrueStudio)</span></div>
<br/>
<div><span>trueStudioBuilder1.ModeToggle = </span><span>True</span></div>
<br/>
<div><span>workPart.ModelingViews.WorkView.RenderingStyle = NXOpen.View.RenderingStyleType.Studio</span></div>
<br/>
<div><span>Dim</span><span> nXObject3 </span><span>As</span><span> NXOpen.NXObject = </span><span>Nothing</span></div>
<div><span>nXObject3 = trueStudioBuilder1.Commit()</span></div>
<br/>
<div><span>trueStudioBuilder1.Destroy()</span></div>
<br/>
<div><span>workPart.ModelingViews.WorkView.RenderingStyle = NXOpen.View.RenderingStyleType.Studio</span></div>
<br/>
<div><span>' ----------------------------------------------</span></div>
<div><span>' 功能表：檔案(F)-&gt;完成草圖(K)</span></div>
<div><span>' ----------------------------------------------</span></div>
<div><span>theSession.DeleteUndoMark(markId11, </span><span>"Curve"</span><span>)</span></div>
<br/>
<div><span>Dim</span><span> sketch2 </span><span>As</span><span> NXOpen.Sketch = </span><span>Nothing</span></div>
<div><span>sketch2 = theSession.ActiveSketch</span></div>
<br/>
<div><span>Dim</span><span> markId12 </span><span>As</span><span> NXOpen.Session.UndoMarkId = </span><span>Nothing</span></div>
<div><span>markId12 = theSession.SetUndoMark(NXOpen.Session.MarkVisibility.Invisible, </span><span>"Deactivate Sketch"</span><span>)</span></div>
<br/>
<div><span>theSession.ActiveSketch.Deactivate(NXOpen.Sketch.ViewReorient.</span><span>True</span><span>, NXOpen.Sketch.UpdateLevel.Model)</span></div>
<br/>
<div><span>' ----------------------------------------------</span></div>
<div><span>' 功能表：插入(S)-&gt;設計特徵(E)-&gt;拉伸(X)...</span></div>
<div><span>' ----------------------------------------------</span></div>
<div><span>Dim</span><span> markId13 </span><span>As</span><span> NXOpen.Session.UndoMarkId = </span><span>Nothing</span></div>
<div><span>markId13 = theSession.SetUndoMark(NXOpen.Session.MarkVisibility.Visible, </span><span>"起點"</span><span>)</span></div>
<br/>
<div><span>Dim</span><span> extrudeBuilder1 </span><span>As</span><span> NXOpen.Features.ExtrudeBuilder = </span><span>Nothing</span></div>
<div><span>extrudeBuilder1 = workPart.Features.CreateExtrudeBuilder(nullNXOpen_Features_Feature)</span></div>
<br/>
<div><span>Dim</span><span> section1 </span><span>As</span><span> NXOpen.Section = </span><span>Nothing</span></div>
<div><span>section1 = workPart.Sections.CreateSection(</span><span>0.0094999999999999998</span><span>, </span><span>0.01</span><span>, </span><span>0.5</span><span>)</span></div>
<br/>
<div><span>extrudeBuilder1.Section = section1</span></div>
<br/>
<div><span>extrudeBuilder1.AllowSelfIntersectingSection(</span><span>True</span><span>)</span></div>
<br/>
<div><span>Dim</span><span> expression23 </span><span>As</span><span> NXOpen.Expression = </span><span>Nothing</span></div>
<div><span>expression23 = workPart.Expressions.CreateSystemExpressionWithUnits(</span><span>"2.00"</span><span>, unit2)</span></div>
<br/>
<div><span>extrudeBuilder1.DistanceTolerance = </span><span>0.01</span></div>
<br/>
<div><span>extrudeBuilder1.BooleanOperation.Type = NXOpen.GeometricUtilities.BooleanOperation.BooleanType.Create</span></div>
<br/>
<div><span>Dim</span><span> targetBodies1(</span><span>0</span><span>) </span><span>As</span><span> NXOpen.Body</span></div>
<div><span>Dim</span><span> nullNXOpen_Body </span><span>As</span><span> NXOpen.Body = </span><span>Nothing</span></div>
<br/>
<div><span>targetBodies1(</span><span>0</span><span>) = nullNXOpen_Body</span></div>
<div><span>extrudeBuilder1.BooleanOperation.SetTargetBodies(targetBodies1)</span></div>
<br/>
<div><span>extrudeBuilder1.Limits.StartExtend.Value.SetFormula(</span><span>"0"</span><span>)</span></div>
<br/>
<div><span>extrudeBuilder1.Limits.EndExtend.Value.SetFormula(</span><span>"25"</span><span>)</span></div>
<br/>
<div><span>extrudeBuilder1.Offset.StartOffset.SetFormula(</span><span>"0"</span><span>)</span></div>
<br/>
<div><span>extrudeBuilder1.Offset.EndOffset.SetFormula(</span><span>"5"</span><span>)</span></div>
<br/>
<div><span>Dim</span><span> smartVolumeProfileBuilder1 </span><span>As</span><span> NXOpen.GeometricUtilities.SmartVolumeProfileBuilder = </span><span>Nothing</span></div>
<div><span>smartVolumeProfileBuilder1 = extrudeBuilder1.SmartVolumeProfile</span></div>
<br/>
<div><span>smartVolumeProfileBuilder1.OpenProfileSmartVolumeOption = </span><span>False</span></div>
<br/>
<div><span>smartVolumeProfileBuilder1.CloseProfileRule = NXOpen.GeometricUtilities.SmartVolumeProfileBuilder.CloseProfileRuleType.Fci</span></div>
<br/>
<div><span>theSession.SetUndoMarkName(markId13, </span><span>"拉伸 對話方塊"</span><span>)</span></div>
<br/>
<div><span>extrudeBuilder1.Limits.StartExtend.Value.SetFormula(</span><span>"0"</span><span>)</span></div>
<br/>
<div><span>extrudeBuilder1.Limits.EndExtend.Value.SetFormula(</span><span>"25"</span><span>)</span></div>
<br/>
<div><span>extrudeBuilder1.Draft.FrontDraftAngle.SetFormula(</span><span>"2"</span><span>)</span></div>
<br/>
<div><span>extrudeBuilder1.Draft.BackDraftAngle.SetFormula(</span><span>"2"</span><span>)</span></div>
<br/>
<div><span>extrudeBuilder1.Offset.StartOffset.SetFormula(</span><span>"0"</span><span>)</span></div>
<br/>
<div><span>extrudeBuilder1.Offset.EndOffset.SetFormula(</span><span>"5"</span><span>)</span></div>
<br/>
<div><span>section1.DistanceTolerance = </span><span>0.01</span></div>
<br/>
<div><span>section1.ChainingTolerance = </span><span>0.0094999999999999998</span></div>
<br/>
<div><span>section1.SetAllowedEntityTypes(NXOpen.Section.AllowTypes.OnlyCurves)</span></div>
<br/>
<div><span>Dim</span><span> markId14 </span><span>As</span><span> NXOpen.Session.UndoMarkId = </span><span>Nothing</span></div>
<div><span>markId14 = theSession.SetUndoMark(NXOpen.Session.MarkVisibility.Invisible, </span><span>"section mark"</span><span>)</span></div>
<br/>
<div><span>Dim</span><span> markId15 </span><span>As</span><span> NXOpen.Session.UndoMarkId = </span><span>Nothing</span></div>
<div><span>markId15 = theSession.SetUndoMark(NXOpen.Session.MarkVisibility.Invisible, </span><span>Nothing</span><span>)</span></div>
<br/>
<div><span>Dim</span><span> features1(</span><span>0</span><span>) </span><span>As</span><span> NXOpen.Features.Feature</span></div>
<div><span>Dim</span><span> sketchFeature1 </span><span>As</span><span> NXOpen.Features.SketchFeature = </span><span>CType</span><span>(feature1, NXOpen.Features.SketchFeature)</span></div>
<br/>
<div><span>features1(</span><span>0</span><span>) = sketchFeature1</span></div>
<div><span>Dim</span><span> curveFeatureRule1 </span><span>As</span><span> NXOpen.CurveFeatureRule = </span><span>Nothing</span></div>
<div><span>curveFeatureRule1 = workPart.ScRuleFactory.CreateRuleCurveFeature(features1)</span></div>
<br/>
<div><span>section1.AllowSelfIntersection(</span><span>True</span><span>)</span></div>
<br/>
<div><span>Dim</span><span> rules1(</span><span>0</span><span>) </span><span>As</span><span> NXOpen.SelectionIntentRule</span></div>
<div><span>rules1(</span><span>0</span><span>) = curveFeatureRule1</span></div>
<div><span>Dim</span><span> helpPoint1 </span><span>As</span><span> NXOpen.Point3d = </span><span>New</span><span> NXOpen.Point3d(-</span><span>1.3642199176742373</span><span>, -</span><span>0.31143699864209995</span><span>, </span><span>0.0</span><span>)</span></div>
<div><span>section1.AddToSection(rules1, arc1, nullNXOpen_NXObject, nullNXOpen_NXObject, helpPoint1, NXOpen.Section.Mode.Create, </span><span>False</span><span>)</span></div>
<br/>
<div><span>theSession.DeleteUndoMark(markId15, </span><span>Nothing</span><span>)</span></div>
<br/>
<div><span>Dim</span><span> direction1 </span><span>As</span><span> NXOpen.Direction = </span><span>Nothing</span></div>
<div><span>direction1 = workPart.Directions.CreateDirection(sketch2, NXOpen.Sense.Forward, NXOpen.SmartObject.UpdateOption.WithinModeling)</span></div>
<br/>
<div><span>extrudeBuilder1.Direction = direction1</span></div>
<br/>
<div><span>Dim</span><span> expression24 </span><span>As</span><span> NXOpen.Expression = </span><span>Nothing</span></div>
<div><span>expression24 = workPart.Expressions.CreateSystemExpressionWithUnits(</span><span>"0"</span><span>, unit1)</span></div>
<br/>
<div><span>theSession.DeleteUndoMark(markId14, </span><span>Nothing</span><span>)</span></div>
<br/>
<div><span>extrudeBuilder1.Limits.EndExtend.Value.SetFormula(</span><span>"6"</span><span>)</span></div>
<br/>
<div><span>Dim</span><span> rotMatrix1 </span><span>As</span><span> NXOpen.Matrix3x3 = </span><span>Nothing</span></div>
<div><span>rotMatrix1.Xx = </span><span>0.34117009820603067</span></div>
<div><span>rotMatrix1.Xy = </span><span>0.93771583394525115</span></div>
<div><span>rotMatrix1.Xz = </span><span>0.065513196063442206</span></div>
<div><span>rotMatrix1.Yx = -</span><span>0.65255317952837755</span></div>
<div><span>rotMatrix1.Yy = </span><span>0.18610108969583089</span></div>
<div><span>rotMatrix1.Yz = </span><span>0.734534364275374</span></div>
<div><span>rotMatrix1.Zx = </span><span>0.67659242678106424</span></div>
<div><span>rotMatrix1.Zy = -</span><span>0.29335200558779939</span></div>
<div><span>rotMatrix1.Zz = </span><span>0.67540157598285466</span></div>
<div><span>Dim</span><span> translation1 </span><span>As</span><span> NXOpen.Point3d = </span><span>New</span><span> NXOpen.Point3d(-</span><span>3.3086805620987789</span><span>, </span><span>0.62693714873927764</span><span>, -</span><span>3.7567940257052665</span><span>)</span></div>
<div><span>workPart.ModelingViews.WorkView.SetRotationTranslationScale(rotMatrix1, translation1, </span><span>20.087236954786007</span><span>)</span></div>
<br/>
<div><span>Dim</span><span> rotMatrix2 </span><span>As</span><span> NXOpen.Matrix3x3 = </span><span>Nothing</span></div>
<div><span>rotMatrix2.Xx = </span><span>0.35230914384389794</span></div>
<div><span>rotMatrix2.Xy = </span><span>0.9320219125607806</span></div>
<div><span>rotMatrix2.Xz = </span><span>0.084931864871331197</span></div>
<div><span>rotMatrix2.Yx = -</span><span>0.80449854395745402</span></div>
<div><span>rotMatrix2.Yy = </span><span>0.25523172209609529</span></div>
<div><span>rotMatrix2.Yz = </span><span>0.53631973747587947</span></div>
<div><span>rotMatrix2.Zx = </span><span>0.47818444133442228</span></div>
<div><span>rotMatrix2.Zy = -</span><span>0.25727790916128879</span></div>
<div><span>rotMatrix2.Zz = </span><span>0.83973074108506962</span></div>
<div><span>Dim</span><span> translation2 </span><span>As</span><span> NXOpen.Point3d = </span><span>New</span><span> NXOpen.Point3d(-</span><span>3.3228413872155782</span><span>, </span><span>0.68621575734774831</span><span>, -</span><span>4.5291485362901351</span><span>)</span></div>
<div><span>workPart.ModelingViews.WorkView.SetRotationTranslationScale(rotMatrix2, translation2, </span><span>20.087236954786007</span><span>)</span></div>
<br/>
<div><span>Dim</span><span> markId16 </span><span>As</span><span> NXOpen.Session.UndoMarkId = </span><span>Nothing</span></div>
<div><span>markId16 = theSession.SetUndoMark(NXOpen.Session.MarkVisibility.Invisible, </span><span>"拉伸"</span><span>)</span></div>
<br/>
<div><span>theSession.DeleteUndoMark(markId16, </span><span>Nothing</span><span>)</span></div>
<br/>
<div><span>Dim</span><span> markId17 </span><span>As</span><span> NXOpen.Session.UndoMarkId = </span><span>Nothing</span></div>
<div><span>markId17 = theSession.SetUndoMark(NXOpen.Session.MarkVisibility.Invisible, </span><span>"拉伸"</span><span>)</span></div>
<br/>
<div><span>extrudeBuilder1.ParentFeatureInternal = </span><span>False</span></div>
<br/>
<div><span>Dim</span><span> feature2 </span><span>As</span><span> NXOpen.Features.Feature = </span><span>Nothing</span></div>
<div><span>feature2 = extrudeBuilder1.CommitFeature()</span></div>
<br/>
<div><span>theSession.DeleteUndoMark(markId17, </span><span>Nothing</span><span>)</span></div>
<br/>
<div><span>theSession.SetUndoMarkName(markId13, </span><span>"拉伸"</span><span>)</span></div>
<br/>
<div><span>Dim</span><span> expression25 </span><span>As</span><span> NXOpen.Expression = extrudeBuilder1.Limits.StartExtend.Value</span></div>
<br/>
<div><span>Dim</span><span> expression26 </span><span>As</span><span> NXOpen.Expression = extrudeBuilder1.Limits.EndExtend.Value</span></div>
<br/>
<div><span>extrudeBuilder1.Destroy()</span></div>
<br/>
<div><span>workPart.Expressions.Delete(expression23)</span></div>
<br/>
<div><span>workPart.Expressions.Delete(expression24)</span></div>
<br/>
<div><span>Dim</span><span> rotMatrix3 </span><span>As</span><span> NXOpen.Matrix3x3 = </span><span>Nothing</span></div>
<div><span>rotMatrix3.Xx = </span><span>0.32369084031626738</span></div>
<div><span>rotMatrix3.Xy = -</span><span>0.25406807483326743</span></div>
<div><span>rotMatrix3.Xz = </span><span>0.91141299817693289</span></div>
<div><span>rotMatrix3.Yx = -</span><span>0.89063788198691607</span></div>
<div><span>rotMatrix3.Yy = </span><span>0.24331311598439376</span></div>
<div><span>rotMatrix3.Yz = </span><span>0.3841391554629961</span></div>
<div><span>rotMatrix3.Zx = -</span><span>0.31935623223166798</span></div>
<div><span>rotMatrix3.Zy = -</span><span>0.93608126834184724</span></div>
<div><span>rotMatrix3.Zz = -</span><span>0.14752442507703645</span></div>
<div><span>Dim</span><span> translation3 </span><span>As</span><span> NXOpen.Point3d = </span><span>New</span><span> NXOpen.Point3d(-</span><span>5.8022847871323835</span><span>, </span><span>1.1427575033863984</span><span>, -</span><span>1.5673830378038165</span><span>)</span></div>
<div><span>workPart.ModelingViews.WorkView.SetRotationTranslationScale(rotMatrix3, translation3, </span><span>20.087236954786007</span><span>)</span></div>
<br/>
<div><span>' ----------------------------------------------</span></div>
<div><span>' 功能表：工具(T)-&gt;動作記錄(J)-&gt;停止錄製(S)</span></div>
<div><span>' ----------------------------------------------</span></div>
<br/>
<div><span>End Sub</span></div>
<div><span>End Module</span></div>
</div>
<p><span></span></p>
<p><br/><br/></p>
<h1 class="post-title">鋼球平衡台 PID 控制</h1>
<p><span> </span><a href="http://229.cycu.org/cd2024_ball_balancing_platform_control_ref.7z">cd2024_ball_balancing_platform_control_ref.7z</a><span>,</span></p>
<p><span> -cd2024_2D Ball Balancer Control using QUARC.pdf</span></p>
<h2 class="post-title">與詳細重點摘要</h2>
<p>1. **實驗前的準備工作**：<br/> - 透過從第一原理出發建立系統模型，包括考慮平衡球和梁的動力學。<br/> - 獲取系統的傳遞函數表示。<br/> - 設計期望的控制響應，確保滿足時間域規格，如百分比超調、峰值時間和穩定時間。</p>
<p>2. **平衡球和梁級聯控制設計**：<br/> - 設計內環控制器：SRV02 PV位置控制器。<br/> - 設計外環控制器，確保平衡球在梁上的位置受控並滿足規格要求。<br/> - 考慮穩態誤差和積分器飽和問題。</p>
<p>3. **實驗操作**：<br/> - 進行位置控制的模擬，包括PD和PID控制器的仿真。<br/> - 實施位置控制，設置Quarc相機塊參數。<br/> - 分析使用PD和PID控制的階躍響應、斜坡響應和正弦響應。</p>
<p>4. **結論**：<br/> - 總結實驗結果，評估控制器性能。<br/> - 探討實驗中遇到的挑戰和解決方案。</p>
<p>以上是詳細重點摘要，涵蓋了實驗前的準備、控制設計、實驗操作和結論部分的關鍵內容。如需進一步了解任何部分，請隨時提出更具體的問題。</p>
<!-- 導入 brython 程式庫 -->
<p>
<script src="/static/brython.js"></script>
<script src="/static/brython_stdlib.js"></script>
</p>
<!-- 啟動 Brython -->
<p>
<script>
window.onload=function(){
brython({debug:1, pythonpath:['/static/','./../downloads/py/']});
}
</script>
</p>
<p><!-- 導入 FileSaver 與 filereader --></p>
<p>
<script src="/static/ace/FileSaver.min.js" type="text/javascript"></script>
<script src="/static/ace/filereader.js" type="text/javascript"></script>
</p>
<p><!-- 導入 ace --></p>
<p>
<script src="/static/ace/ace.js" type="text/javascript"></script>
<script src="/static/ace/ext-language_tools.js" type="text/javascript"></script>
<script src="/static/ace/mode-python3.js" type="text/javascript"></script>
<script src="/static/ace/snippets/python.js" type="text/javascript"></script>
</p>
<p><!-- 導入 gearUtils-0.9.js Cango 齒輪繪圖程式庫 -->
<script src="/static/Cango-24v03-min.js"></script>
<script src="/static/gearUtils-09.js"></script>
<script src="/static/SVGpathUtils-6v03-min.js"></script>
<script src="/static/sylvester.js"></script>
<script src="/static/PrairieDraw.js"></script>
</p>
<p><!-- 請注意, 這裡使用 Javascript 將 localStorage["kw_py_src1"] 中存在近端瀏覽器的程式碼, 由使用者決定存檔名稱--></p>
<p>
<script type="text/javascript">
function doSave(storage_id, filename){
    var blob = new Blob([localStorage[storage_id]], {type: "text/plain;charset=utf-8"});
    filename = document.getElementById(filename).value
    saveAs(blob, filename+".py");
}
</script>
</p>
<p>
<script type="text/python3">
from browser import document as doc
import ace
# 清除畫布
def clear_bd1(ev):
    bd = doc["brython_div1"]
    bd.clear()
Ace1 = ace.Editor(editor_id="kw_editor1", console_id="kw_console1", container_id="kw__container1", storage_id="kw_py_src1" )
# 從 gist 取出程式碼後, 放入 editor 作為 default 程式
def run1():
    # 利用 get 取下 src 變數值
    try:
        url = doc.query["src"]
    except:
        url = "https://gist.githubusercontent.com/mdecourse/0229a8a017091476a79700b8a190f185/raw/c3a6deaf717f8f2739a4b1392a5ab10936e9693a/from_1_add_to_10_1.py"
    prog = open(url).read()

    # 將程式載入編輯區
    Ace1.editor.setValue(prog)
    Ace1.editor.scrollToRow(0)
    Ace1.editor.gotoLine(0)
    # 直接執行程式
    #ns = {'__name__':'__main__'}
    #exec(prog, ns)
    # 按下 run 按鈕
    Ace1.run()

# 執行程式, 顯示輸出結果與清除輸出結果及對應按鈕綁定
doc['kw_run1'].bind('click', Ace1.run)
doc['kw_show_console1'].bind('click', Ace1.show_console)
doc['kw_clear_console1'].bind('click', Ace1.clear_console)
doc['clear_bd1'].bind('click', clear_bd1)
# 呼叫函式執行
run1()
</script>
</p>
<p><!-- add 1 to 100 開始 -->
<script type="text/python3">
from browser import document as doc
import ace

# 清除畫布
def clear_bd1(ev):
    bd = doc["brython_div1"]
    bd.clear()

# 利用 ace 中的 Editor 建立 Ace2 物件, 其中的輸入變數分別對應到頁面中的編輯區物件
Ace2 = ace.Editor(editor_id="kw_editor1", console_id="kw_console1", container_id="kw__container1", storage_id="kw_py_src1" )

add1to100_url = "https://gist.githubusercontent.com/mdecourse/0229a8a017091476a79700b8a190f185/raw/c48e37714f055c3a0027cbfef59e442a6ef659b9/from_1_add_to_100_1.py"

# 從 gist 取得程式碼
add_src = open(add1to100_url).read()
def add(ev):
    Ace2.editor.setValue(add_src)
    Ace2.editor.scrollToRow(0)
    Ace2.editor.gotoLine(0)
    Ace2.run()

# id 為 "add1to100" 的按鈕點按時, 執行 add 方法
doc["add1to100"].bind('click', add)
</script>
</p>
<p><!-- add 1 to 100 結束--></p>
<!-- editor1 開始 -->
<p><!-- 用來顯示程式碼的 editor 區域 --></p>
<div id="kw_editor1" style="width: 600px; height: 300px;">
<h1 class="post-title">都靈理工大學</h1>
<p><span>由各組員在其個人的 cd2024 倉儲中, 以 LaTeX 格式分工完成下列文章的英文與中文翻譯並列資料, 最後在分組網站的 Release 或 downloads 區完成 2b-midbgx_report.pdf 的製作.</span></p>
<p><span>41123207 王騰甫分工:</span><span> <a href="https://mdecd2024.github.io/2b-midbg4/downloads/2.pdf">2.pdf</a></span></p>
<p><span></span></p>
<h1>教學影片分組整理</h1>
<p>在影片上填上字幕, 另行上傳到可以嵌入到各分組的網站上</p>
<p><span>41123207 王騰甫分工:</span></p>
<p><a href="https://drive.google.com/file/d/1j3XLXk12sSlkadwDROiQokf6wojutBmu/view?usp=drive_link">cd2024 2b w4 利用 Gitpod 與個人 token 取得分組倉儲改版權限 13</a></p>
<p><a href="https://drive.google.com/file/d/1w5HH7TFH38vEABh7ss6smWq3lTJ_FY-p/view?usp=drive_link">cd2024 2b w5 指定影片加註任務 統整網誌以及配置 NX 可攜與 PC 執行規劃14</a></p>
<p></p>
<p></p>
<br/>
<h1>教學影片分組整理逐字稿</h1>
<p>從影片字幕中整理出逐字稿, 放在影片下方, 以 .txt 連結安排</p>
<p><span>41123207 王騰甫分工:</span></p>
<p><a href="https://mdecd2024.github.io/2b-midbg4/downloads/cd2024%202b%20w4%20%E5%88%A9%E7%94%A8%20Gitpod%20%E8%88%87%E5%80%8B%E4%BA%BA%20token%20%E5%8F%96%E5%BE%97%E5%88%86%E7%B5%84%E5%80%89%E5%84%B2%E6%94%B9%E7%89%88%E6%AC%8A%E9%99%90%2013.txt">cd2024 2b w4 利用 Gitpod 與個人 token 取得分組倉儲改版權限 13.txt</a></p>
<p><a href="https://mdecd2024.github.io/2b-midbg4/downloads/cd2024%202b%20w5%20%E6%8C%87%E5%AE%9A%E5%BD%B1%E7%89%87%E5%8A%A0%E8%A8%BB%E4%BB%BB%E5%8B%99%20%E7%B5%B1%E6%95%B4%E7%B6%B2%E8%AA%8C%E4%BB%A5%E5%8F%8A%E9%85%8D%E7%BD%AE%20NX%20%E5%8F%AF%E6%94%9C%E8%88%87%20PC%20%E5%9F%B7%E8%A1%8C%E8%A6%8F%E5%8A%83%2014.txt">cd2024 2b w5 指定影片加註任務 統整網誌以及配置 NX 可攜與 PC 執行規劃 14.txt</a></p>
<p></p>
<p><br/><span></span></p>
</div>
<div style="width: 600px; height: 300px;"><br/><br/></div>
<p><!-- 以下的表單與按鈕與前面的 Javascript doSave 函式以及 FileSaver.min.js 互相配合 --></p>
<p><!-- 存擋表單開始 --></p>
<form><label>Filename: <input id="kw_filename" placeholder="input file name" type="text"/>.py</label> <input onclick="doSave('kw_py_src1', 'kw_filename1');" type="submit" value="Save"/></form>
<p><!-- 存擋表單結束 --></p>
<p></p>
<p><!-- 執行與清除按鈕開始 --></p>
<p><button id="kw_run1">Run</button> <button id="kw_show_console1">Output</button> <button id="kw_clear_console1">清除輸出區</button><button id="clear_bd1">清除繪圖區</button><button onclick="window.location.reload()">Reload</button></p>
<p><!-- 執行與清除按鈕結束 --></p>
<p></p>
<p><!-- 程式執行 ouput 區 --></p>
<div style="width: 100%; height: 100%;"><textarea autocomplete="off" id="kw_console1"></textarea></div>
<p><!-- Brython 程式執行的結果, 都以 brython_div1 作為切入位置 --></p>
<div id="brython_div1"></div>
<!-- editor1 結束 --><hr/><!-- ########################################## -->
<p>從 1 累加到 100 part2:</p>
<p><button id="add1to100part2">1 add to 100</button><button id="cango_three_gears">cango_three_gears</button><button id="bsnake">BSnake</button><button id="aitetris">AI Tetris</button><button id="threejsblock">Rotating Block</button></p>
<p><!-- 請注意, 這裡使用 Javascript 將 localStorage["kw_py_src2"] 中存在近端瀏覽器的程式碼, 由使用者決定存檔名稱--></p>
<p>
<script type="text/python3">
from browser import document as doc
import ace
# 清除畫布
def clear_bd2(ev):
    bd = doc["brython_div2"]
    bd.clear()
Ace3 = ace.Editor(editor_id="kw_editor2", console_id="kw_console2", container_id="kw__container2", storage_id="kw_py_src2" )
# 從 gist 取出程式碼後, 放入 editor 作為 default 程式
def run2():
    # 利用 get 取下 src 變數值
    try:
        url = doc.query["src2"]
    except:
        url = "https://gist.githubusercontent.com/mdecourse/0229a8a017091476a79700b8a190f185/raw/c3a6deaf717f8f2739a4b1392a5ab10936e9693a/from_1_add_to_10_1.py"
    prog = open(url).read()

    # 將程式載入編輯區
    Ace3.editor.setValue(prog)
    Ace3.editor.scrollToRow(0)
    Ace3.editor.gotoLine(0)
    # 直接執行程式
    #ns = {'__name__':'__main__'}
    #exec(prog, ns)
    # 按下 run 按鈕
    Ace3.run()

# 執行程式, 顯示輸出結果與清除輸出結果及對應按鈕綁定
doc['kw_run2'].bind('click', Ace3.run)
doc['kw_show_console2'].bind('click', Ace3.show_console)
doc['kw_clear_console2'].bind('click', Ace3.clear_console)
doc['clear_bd2'].bind('click', clear_bd2)
# 呼叫函式執行
run2()
</script>
</p>
<p><!-- add 1 to 100 part2 開始 -->
<script type="text/python3">
from browser import document as doc
import ace

# 清除畫布
def clear_bd2(ev):
    bd = doc["brython_div2"]
    bd.clear()

# 利用 ace 中的 Editor 建立 Ace2 物件, 其中的輸入變數分別對應到頁面中的編輯區物件
Ace4 = ace.Editor(editor_id="kw_editor2", console_id="kw_console2", container_id="kw__container2", storage_id="kw_py_src2" )

# 透過 Ace4 以類別建立一個通用的 button2, 可以在多個案例中將 gist 程導入編輯區

class button2:
    def __init__(self, url):
        self.url = url

    # 記得加入 event 輸入變數
    def do(self,ev):
        Ace4.editor.setValue(open(self.url).read())
        Ace4.editor.scrollToRow(0)
        Ace4.editor.gotoLine(0)
        Ace4.run()

add1to100_url = "https://gist.githubusercontent.com/mdecourse/0229a8a017091476a79700b8a190f185/raw/c48e37714f055c3a0027cbfef59e442a6ef659b9/from_1_add_to_100_1.py"

# 從 gist 取得程式碼
add_src = open(add1to100_url).read()
def add2(ev):
    Ace4.editor.setValue(add_src)
    Ace4.editor.scrollToRow(0)
    Ace4.editor.gotoLine(0)
    Ace4.run()

# id 為 "add1to100part2" 的按鈕點按時, 執行 add 方法
doc["add1to100part2"].bind('click', add2)
# 以下為運用 button2 class 的通用 gist 程式導入區
################################## cango_three_gears start
cango_three_gears_url = "https://gist.githubusercontent.com/mdecycu/d9082d678096bd58378d6afe2c7fa05d/raw/f7a85d737d6723d5e34c526d5daee990ed92c32b/cango_three_gears_brython_div2.py"
cango_three_gears = button2(cango_three_gears_url)
doc["cango_three_gears"].bind("click", cango_three_gears.do)
################################## cango_three_gears end
################################## bsnake start
bsnake_url = "https://gist.githubusercontent.com/mdecycu/d9082d678096bd58378d6afe2c7fa05d/raw/f7a85d737d6723d5e34c526d5daee990ed92c32b/kmol_snakey.py"
bsnake = button2(bsnake_url)
doc["bsnake"].bind("click", bsnake.do)
################################## bsnake end
################################## aitetris start
aitetris_url = "https://gist.githubusercontent.com/mdecycu/d9082d678096bd58378d6afe2c7fa05d/raw/f7a85d737d6723d5e34c526d5daee990ed92c32b/pygame_to_brython_tetris_ai.py"
aitetris = button2(aitetris_url)
doc["aitetris"].bind("click", aitetris.do)
################################## aitetris end
################################## threejsblock start
threejsblock_url = "https://gist.githubusercontent.com/mdecycu/2c6323eff49b496d1bafd210f3ec9707/raw/df37802f9e8a386b6424f7945af622b1cd0a9ca5/threejs_rotating_block.py"
threejsblock = button2(threejsblock_url)
doc["threejsblock"].bind("click", threejsblock.do)
################################## threejsblock end
</script>
</p>
<p><!-- add 1 to 100 part2 結束--></p>
<!-- editor2 開始 -->
<p><!-- 用來顯示程式碼的 editor 區域 --></p>
<div id="kw_editor2" style="width: 600px; height: 300px;"></div>
<p><!-- 以下的表單與按鈕與前面的 Javascript doSave 函式以及 FileSaver.min.js 互相配合 --></p>
<p><!-- 存擋表單開始 --></p>
<form><label>Filename: <input id="kw_filename2" placeholder="input file name" type="text"/>.py</label> <input onclick="doSave('kw_py_src2', 'kw_filename2');" type="submit" value="Save"/></form>
<p><!-- 存擋表單結束 --></p>
<p></p>
<p><!-- 執行與清除按鈕開始 --></p>
<p><button id="kw_run2">Run</button> <button id="kw_show_console2">Output</button> <button id="kw_clear_console2">清除輸出區</button><button id="clear_bd2">清除繪圖區</button><button onclick="window.location.reload()">Reload</button></p>
<p><!-- 執行與清除按鈕結束 --></p>
<p></p>
<p><!-- 程式執行 ouput 區 --></p>
<div style="width: 100%; height: 100%;"><textarea autocomplete="off" id="kw_console2"></textarea></div>
<p><!-- Brython 程式執行的結果, 都以 brython_div1 作為切入位置 --></p>
<div id="brython_div2"></div>
<!-- editor2 結束 --><hr/>
<p>
<script src="https://unpkg.com/three@0.144.0/build/three.js" type="text/javascript"></script>
</p>